module
public import Ryser.TwoResidualSets
public import Ryser.Theory.TemplateData
@[expose] public section
set_option maxRecDepth 8192
set_option maxHeartbeats 2000000
set_option linter.unusedVariables false
namespace Ryser.WitnessCases.Row80_105154556379.Cover
open FiniteBox TwoResidualSets
theorem actual485 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 0 ∨ b0 1 = 0 ∨ b0 2 = 1 ∨ b0 3 = 0 ∨ b0 0 = 3 ∨ b0 1 = 3 ∨ b0 2 = 0 ∨ b0 3 = 2 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb0
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 2) ∨ (0 = b0 0 ∨ 0 = b0 1 ∨ 1 = b0 2 ∨ 0 = b0 3) ∨ (3 = b0 0 ∨ 3 = b0 1 ∨ 0 = b0 2 ∨ 2 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual486 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    : b2 0 = 0 ∨ b2 1 = 0 ∨ b2 2 = 1 ∨ b2 3 = 0 ∨ b2 0 = 3 ∨ b2 1 = 3 ∨ b2 2 = 0 ∨ b2 3 = 2 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb2
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 2) ∨ (0 = b2 0 ∨ 0 = b2 1 ∨ 1 = b2 2 ∨ 0 = b2 3) ∨ (3 = b2 0 ∨ 3 = b2 1 ∨ 0 = b2 2 ∨ 2 = b2 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual487 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b4 : NatEdge) (hb4 : b4 ∈ H)
    : b4 0 = 0 ∨ b4 1 = 0 ∨ b4 2 = 1 ∨ b4 3 = 0 ∨ b4 0 = 3 ∨ b4 1 = 3 ∨ b4 2 = 0 ∨ b4 3 = 2 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb4
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 2) ∨ (0 = b4 0 ∨ 0 = b4 1 ∨ 1 = b4 2 ∨ 0 = b4 3) ∨ (3 = b4 0 ∨ 3 = b4 1 ∨ 0 = b4 2 ∨ 2 = b4 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual488 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b8 : NatEdge) (hb8 : b8 ∈ H)
    : b8 0 = 0 ∨ b8 1 = 0 ∨ b8 2 = 1 ∨ b8 3 = 0 ∨ b8 0 = 3 ∨ b8 1 = 3 ∨ b8 2 = 0 ∨ b8 3 = 2 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb8
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 2) ∨ (0 = b8 0 ∨ 0 = b8 1 ∨ 1 = b8 2 ∨ 0 = b8 3) ∨ (3 = b8 0 ∨ 3 = b8 1 ∨ 0 = b8 2 ∨ 2 = b8 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual489 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    : b12 0 = 0 ∨ b12 1 = 0 ∨ b12 2 = 1 ∨ b12 3 = 0 ∨ b12 0 = 3 ∨ b12 1 = 3 ∨ b12 2 = 0 ∨ b12 3 = 2 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb12
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 2) ∨ (0 = b12 0 ∨ 0 = b12 1 ∨ 1 = b12 2 ∨ 0 = b12 3) ∨ (3 = b12 0 ∨ 3 = b12 1 ∨ 0 = b12 2 ∨ 2 = b12 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual490 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    : b13 0 = 0 ∨ b13 1 = 0 ∨ b13 2 = 1 ∨ b13 3 = 0 ∨ b13 0 = 3 ∨ b13 1 = 3 ∨ b13 2 = 0 ∨ b13 3 = 2 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb13
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 2) ∨ (0 = b13 0 ∨ 0 = b13 1 ∨ 1 = b13 2 ∨ 0 = b13 3) ∨ (3 = b13 0 ∨ 3 = b13 1 ∨ 0 = b13 2 ∨ 2 = b13 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual491 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b16 : NatEdge) (hb16 : b16 ∈ H)
    : b16 0 = 0 ∨ b16 1 = 0 ∨ b16 2 = 1 ∨ b16 3 = 0 ∨ b16 0 = 3 ∨ b16 1 = 3 ∨ b16 2 = 0 ∨ b16 3 = 2 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb16
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 2) ∨ (0 = b16 0 ∨ 0 = b16 1 ∨ 1 = b16 2 ∨ 0 = b16 3) ∨ (3 = b16 0 ∨ 3 = b16 1 ∨ 0 = b16 2 ∨ 2 = b16 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual492 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 0 ∨ b0 1 = 0 ∨ b0 2 = 1 ∨ b0 3 = 0 ∨ b0 0 = 4 ∨ b0 1 = 4 ∨ b0 2 = 0 ∨ b0 3 = 2 := by
  have ht := no_three_hits noThree (hF 0) (hF 4) hb0
  change (0 = 4 ∨ 0 = 4 ∨ 1 = 0 ∨ 0 = 2) ∨ (0 = b0 0 ∨ 0 = b0 1 ∨ 1 = b0 2 ∨ 0 = b0 3) ∨ (4 = b0 0 ∨ 4 = b0 1 ∨ 0 = b0 2 ∨ 2 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual493 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    : b2 0 = 0 ∨ b2 1 = 0 ∨ b2 2 = 1 ∨ b2 3 = 0 ∨ b2 0 = 4 ∨ b2 1 = 4 ∨ b2 2 = 0 ∨ b2 3 = 2 := by
  have ht := no_three_hits noThree (hF 0) (hF 4) hb2
  change (0 = 4 ∨ 0 = 4 ∨ 1 = 0 ∨ 0 = 2) ∨ (0 = b2 0 ∨ 0 = b2 1 ∨ 1 = b2 2 ∨ 0 = b2 3) ∨ (4 = b2 0 ∨ 4 = b2 1 ∨ 0 = b2 2 ∨ 2 = b2 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual494 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b8 : NatEdge) (hb8 : b8 ∈ H)
    : b8 0 = 0 ∨ b8 1 = 0 ∨ b8 2 = 1 ∨ b8 3 = 0 ∨ b8 0 = 4 ∨ b8 1 = 4 ∨ b8 2 = 0 ∨ b8 3 = 2 := by
  have ht := no_three_hits noThree (hF 0) (hF 4) hb8
  change (0 = 4 ∨ 0 = 4 ∨ 1 = 0 ∨ 0 = 2) ∨ (0 = b8 0 ∨ 0 = b8 1 ∨ 1 = b8 2 ∨ 0 = b8 3) ∨ (4 = b8 0 ∨ 4 = b8 1 ∨ 0 = b8 2 ∨ 2 = b8 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual495 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    : b12 0 = 0 ∨ b12 1 = 0 ∨ b12 2 = 1 ∨ b12 3 = 0 ∨ b12 0 = 4 ∨ b12 1 = 4 ∨ b12 2 = 0 ∨ b12 3 = 2 := by
  have ht := no_three_hits noThree (hF 0) (hF 4) hb12
  change (0 = 4 ∨ 0 = 4 ∨ 1 = 0 ∨ 0 = 2) ∨ (0 = b12 0 ∨ 0 = b12 1 ∨ 1 = b12 2 ∨ 0 = b12 3) ∨ (4 = b12 0 ∨ 4 = b12 1 ∨ 0 = b12 2 ∨ 2 = b12 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual496 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    : b13 0 = 0 ∨ b13 1 = 0 ∨ b13 2 = 1 ∨ b13 3 = 0 ∨ b13 0 = 4 ∨ b13 1 = 4 ∨ b13 2 = 0 ∨ b13 3 = 2 := by
  have ht := no_three_hits noThree (hF 0) (hF 4) hb13
  change (0 = 4 ∨ 0 = 4 ∨ 1 = 0 ∨ 0 = 2) ∨ (0 = b13 0 ∨ 0 = b13 1 ∨ 1 = b13 2 ∨ 0 = b13 3) ∨ (4 = b13 0 ∨ 4 = b13 1 ∨ 0 = b13 2 ∨ 2 = b13 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual497 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    : b14 0 = 0 ∨ b14 1 = 0 ∨ b14 2 = 1 ∨ b14 3 = 0 ∨ b14 0 = 4 ∨ b14 1 = 4 ∨ b14 2 = 0 ∨ b14 3 = 2 := by
  have ht := no_three_hits noThree (hF 0) (hF 4) hb14
  change (0 = 4 ∨ 0 = 4 ∨ 1 = 0 ∨ 0 = 2) ∨ (0 = b14 0 ∨ 0 = b14 1 ∨ 1 = b14 2 ∨ 0 = b14 3) ∨ (4 = b14 0 ∨ 4 = b14 1 ∨ 0 = b14 2 ∨ 2 = b14 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual498 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b16 : NatEdge) (hb16 : b16 ∈ H)
    : b16 0 = 0 ∨ b16 1 = 0 ∨ b16 2 = 1 ∨ b16 3 = 0 ∨ b16 0 = 4 ∨ b16 1 = 4 ∨ b16 2 = 0 ∨ b16 3 = 2 := by
  have ht := no_three_hits noThree (hF 0) (hF 4) hb16
  change (0 = 4 ∨ 0 = 4 ∨ 1 = 0 ∨ 0 = 2) ∨ (0 = b16 0 ∨ 0 = b16 1 ∨ 1 = b16 2 ∨ 0 = b16 3) ∨ (4 = b16 0 ∨ 4 = b16 1 ∨ 0 = b16 2 ∨ 2 = b16 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual499 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 80 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    : b0 0 = 0 ∨ b0 1 = 0 ∨ b0 2 = 1 ∨ b0 3 = 0 ∨ b2 0 = 0 ∨ b2 1 = 0 ∨ b2 2 = 1 ∨ b2 3 = 0 ∨ b0 0 = b2 0 ∨ b0 1 = b2 1 ∨ b0 2 = b2 2 ∨ b0 3 = b2 3 := by
  have ht := no_three_hits noThree (hF 0) hb0 hb2
  change (0 = b0 0 ∨ 0 = b0 1 ∨ 1 = b0 2 ∨ 0 = b0 3) ∨ (0 = b2 0 ∨ 0 = b2 1 ∨ 1 = b2 2 ∨ 0 = b2 3) ∨ (b0 0 = b2 0 ∨ b0 1 = b2 1 ∨ b0 2 = b2 2 ∨ b0 3 = b2 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))

#print axioms actual499
end Ryser.WitnessCases.Row80_105154556379.Cover
