module
public import Ryser.TwoResidualSets
public import Ryser.Theory.TemplateData
@[expose] public section
set_option maxRecDepth 8192
set_option maxHeartbeats 2000000
set_option linter.unusedVariables false
namespace Ryser.WitnessCases.ResidualRow172_1225378239794.Cover
open FiniteBox TwoResidualSets
theorem actual1846 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    : b12 0 = 2 ∨ b12 1 = 2 ∨ b12 2 = 0 ∨ b12 3 = 3 ∨ b12 0 = 4 ∨ b12 1 = 4 ∨ b12 2 = 1 ∨ b12 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 4) hb12
  change (2 = 4 ∨ 2 = 4 ∨ 0 = 1 ∨ 3 = 0) ∨ (2 = b12 0 ∨ 2 = b12 1 ∨ 0 = b12 2 ∨ 3 = b12 3) ∨ (4 = b12 0 ∨ 4 = b12 1 ∨ 1 = b12 2 ∨ 0 = b12 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1847 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    : b13 0 = 2 ∨ b13 1 = 2 ∨ b13 2 = 0 ∨ b13 3 = 3 ∨ b13 0 = 4 ∨ b13 1 = 4 ∨ b13 2 = 1 ∨ b13 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 4) hb13
  change (2 = 4 ∨ 2 = 4 ∨ 0 = 1 ∨ 3 = 0) ∨ (2 = b13 0 ∨ 2 = b13 1 ∨ 0 = b13 2 ∨ 3 = b13 3) ∨ (4 = b13 0 ∨ 4 = b13 1 ∨ 1 = b13 2 ∨ 0 = b13 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1848 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    : b14 0 = 2 ∨ b14 1 = 2 ∨ b14 2 = 0 ∨ b14 3 = 3 ∨ b14 0 = 4 ∨ b14 1 = 4 ∨ b14 2 = 1 ∨ b14 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 4) hb14
  change (2 = 4 ∨ 2 = 4 ∨ 0 = 1 ∨ 3 = 0) ∨ (2 = b14 0 ∨ 2 = b14 1 ∨ 0 = b14 2 ∨ 3 = b14 3) ∨ (4 = b14 0 ∨ 4 = b14 1 ∨ 1 = b14 2 ∨ 0 = b14 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1849 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b15 : NatEdge) (hb15 : b15 ∈ H)
    : b15 0 = 2 ∨ b15 1 = 2 ∨ b15 2 = 0 ∨ b15 3 = 3 ∨ b15 0 = 4 ∨ b15 1 = 4 ∨ b15 2 = 1 ∨ b15 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 4) hb15
  change (2 = 4 ∨ 2 = 4 ∨ 0 = 1 ∨ 3 = 0) ∨ (2 = b15 0 ∨ 2 = b15 1 ∨ 0 = b15 2 ∨ 3 = b15 3) ∨ (4 = b15 0 ∨ 4 = b15 1 ∨ 1 = b15 2 ∨ 0 = b15 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1850 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b18 : NatEdge) (hb18 : b18 ∈ H)
    : b18 0 = 2 ∨ b18 1 = 2 ∨ b18 2 = 0 ∨ b18 3 = 3 ∨ b18 0 = 4 ∨ b18 1 = 4 ∨ b18 2 = 1 ∨ b18 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 4) hb18
  change (2 = 4 ∨ 2 = 4 ∨ 0 = 1 ∨ 3 = 0) ∨ (2 = b18 0 ∨ 2 = b18 1 ∨ 0 = b18 2 ∨ 3 = b18 3) ∨ (4 = b18 0 ∨ 4 = b18 1 ∨ 1 = b18 2 ∨ 0 = b18 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1851 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b19 : NatEdge) (hb19 : b19 ∈ H)
    : b19 0 = 2 ∨ b19 1 = 2 ∨ b19 2 = 0 ∨ b19 3 = 3 ∨ b19 0 = 4 ∨ b19 1 = 4 ∨ b19 2 = 1 ∨ b19 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 4) hb19
  change (2 = 4 ∨ 2 = 4 ∨ 0 = 1 ∨ 3 = 0) ∨ (2 = b19 0 ∨ 2 = b19 1 ∨ 0 = b19 2 ∨ 3 = b19 3) ∨ (4 = b19 0 ∨ 4 = b19 1 ∨ 1 = b19 2 ∨ 0 = b19 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1852 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b20 : NatEdge) (hb20 : b20 ∈ H)
    : b20 0 = 2 ∨ b20 1 = 2 ∨ b20 2 = 0 ∨ b20 3 = 3 ∨ b20 0 = 4 ∨ b20 1 = 4 ∨ b20 2 = 1 ∨ b20 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 4) hb20
  change (2 = 4 ∨ 2 = 4 ∨ 0 = 1 ∨ 3 = 0) ∨ (2 = b20 0 ∨ 2 = b20 1 ∨ 0 = b20 2 ∨ 3 = b20 3) ∨ (4 = b20 0 ∨ 4 = b20 1 ∨ 1 = b20 2 ∨ 0 = b20 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1853 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b21 : NatEdge) (hb21 : b21 ∈ H)
    : b21 0 = 2 ∨ b21 1 = 2 ∨ b21 2 = 0 ∨ b21 3 = 3 ∨ b21 0 = 4 ∨ b21 1 = 4 ∨ b21 2 = 1 ∨ b21 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 4) hb21
  change (2 = 4 ∨ 2 = 4 ∨ 0 = 1 ∨ 3 = 0) ∨ (2 = b21 0 ∨ 2 = b21 1 ∨ 0 = b21 2 ∨ 3 = b21 3) ∨ (4 = b21 0 ∨ 4 = b21 1 ∨ 1 = b21 2 ∨ 0 = b21 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1854 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b23 0 = 2 ∨ b23 1 = 2 ∨ b23 2 = 0 ∨ b23 3 = 3 ∨ b23 0 = 4 ∨ b23 1 = 4 ∨ b23 2 = 1 ∨ b23 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 4) hb23
  change (2 = 4 ∨ 2 = 4 ∨ 0 = 1 ∨ 3 = 0) ∨ (2 = b23 0 ∨ 2 = b23 1 ∨ 0 = b23 2 ∨ 3 = b23 3) ∨ (4 = b23 0 ∨ 4 = b23 1 ∨ 1 = b23 2 ∨ 0 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1855 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b29 : NatEdge) (hb29 : b29 ∈ H)
    : b29 0 = 2 ∨ b29 1 = 2 ∨ b29 2 = 0 ∨ b29 3 = 3 ∨ b29 0 = 4 ∨ b29 1 = 4 ∨ b29 2 = 1 ∨ b29 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 4) hb29
  change (2 = 4 ∨ 2 = 4 ∨ 0 = 1 ∨ 3 = 0) ∨ (2 = b29 0 ∨ 2 = b29 1 ∨ 0 = b29 2 ∨ 3 = b29 3) ∨ (4 = b29 0 ∨ 4 = b29 1 ∨ 1 = b29 2 ∨ 0 = b29 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1856 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 2 ∨ b0 1 = 2 ∨ b0 2 = 0 ∨ b0 3 = 3 ∨ b0 0 = 5 ∨ b0 1 = 5 ∨ b0 2 = 2 ∨ b0 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 5) hb0
  change (2 = 5 ∨ 2 = 5 ∨ 0 = 2 ∨ 3 = 0) ∨ (2 = b0 0 ∨ 2 = b0 1 ∨ 0 = b0 2 ∨ 3 = b0 3) ∨ (5 = b0 0 ∨ 5 = b0 1 ∨ 2 = b0 2 ∨ 0 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1857 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b1 : NatEdge) (hb1 : b1 ∈ H)
    : b1 0 = 2 ∨ b1 1 = 2 ∨ b1 2 = 0 ∨ b1 3 = 3 ∨ b1 0 = 5 ∨ b1 1 = 5 ∨ b1 2 = 2 ∨ b1 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 5) hb1
  change (2 = 5 ∨ 2 = 5 ∨ 0 = 2 ∨ 3 = 0) ∨ (2 = b1 0 ∨ 2 = b1 1 ∨ 0 = b1 2 ∨ 3 = b1 3) ∨ (5 = b1 0 ∨ 5 = b1 1 ∨ 2 = b1 2 ∨ 0 = b1 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1858 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    : b12 0 = 2 ∨ b12 1 = 2 ∨ b12 2 = 0 ∨ b12 3 = 3 ∨ b12 0 = 5 ∨ b12 1 = 5 ∨ b12 2 = 2 ∨ b12 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 5) hb12
  change (2 = 5 ∨ 2 = 5 ∨ 0 = 2 ∨ 3 = 0) ∨ (2 = b12 0 ∨ 2 = b12 1 ∨ 0 = b12 2 ∨ 3 = b12 3) ∨ (5 = b12 0 ∨ 5 = b12 1 ∨ 2 = b12 2 ∨ 0 = b12 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1859 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    : b13 0 = 2 ∨ b13 1 = 2 ∨ b13 2 = 0 ∨ b13 3 = 3 ∨ b13 0 = 5 ∨ b13 1 = 5 ∨ b13 2 = 2 ∨ b13 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 5) hb13
  change (2 = 5 ∨ 2 = 5 ∨ 0 = 2 ∨ 3 = 0) ∨ (2 = b13 0 ∨ 2 = b13 1 ∨ 0 = b13 2 ∨ 3 = b13 3) ∨ (5 = b13 0 ∨ 5 = b13 1 ∨ 2 = b13 2 ∨ 0 = b13 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1860 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b18 : NatEdge) (hb18 : b18 ∈ H)
    : b18 0 = 2 ∨ b18 1 = 2 ∨ b18 2 = 0 ∨ b18 3 = 3 ∨ b18 0 = 5 ∨ b18 1 = 5 ∨ b18 2 = 2 ∨ b18 3 = 0 := by
  have ht := no_three_hits noThree (hF 2) (hF 5) hb18
  change (2 = 5 ∨ 2 = 5 ∨ 0 = 2 ∨ 3 = 0) ∨ (2 = b18 0 ∨ 2 = b18 1 ∨ 0 = b18 2 ∨ 3 = b18 3) ∨ (5 = b18 0 ∨ 5 = b18 1 ∨ 2 = b18 2 ∨ 0 = b18 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))

#print axioms actual1860
end Ryser.WitnessCases.ResidualRow172_1225378239794.Cover
