module
public import Ryser.TwoResidualSets
public import Ryser.Theory.TemplateData
@[expose] public section
set_option maxRecDepth 8192
set_option maxHeartbeats 2000000
set_option linter.unusedVariables false
namespace Ryser.WitnessCases.ResidualRow172_1225378239794.Cover
open FiniteBox TwoResidualSets
theorem actual1636 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 0 ∨ b0 1 = 0 ∨ b0 2 = 0 ∨ b0 3 = 1 ∨ b0 0 = 3 ∨ b0 1 = 3 ∨ b0 2 = 1 ∨ b0 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb0
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b0 0 ∨ 0 = b0 1 ∨ 0 = b0 2 ∨ 1 = b0 3) ∨ (3 = b0 0 ∨ 3 = b0 1 ∨ 1 = b0 2 ∨ 0 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1637 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b1 : NatEdge) (hb1 : b1 ∈ H)
    : b1 0 = 0 ∨ b1 1 = 0 ∨ b1 2 = 0 ∨ b1 3 = 1 ∨ b1 0 = 3 ∨ b1 1 = 3 ∨ b1 2 = 1 ∨ b1 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb1
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b1 0 ∨ 0 = b1 1 ∨ 0 = b1 2 ∨ 1 = b1 3) ∨ (3 = b1 0 ∨ 3 = b1 1 ∨ 1 = b1 2 ∨ 0 = b1 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1638 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    : b12 0 = 0 ∨ b12 1 = 0 ∨ b12 2 = 0 ∨ b12 3 = 1 ∨ b12 0 = 3 ∨ b12 1 = 3 ∨ b12 2 = 1 ∨ b12 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb12
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b12 0 ∨ 0 = b12 1 ∨ 0 = b12 2 ∨ 1 = b12 3) ∨ (3 = b12 0 ∨ 3 = b12 1 ∨ 1 = b12 2 ∨ 0 = b12 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1639 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    : b13 0 = 0 ∨ b13 1 = 0 ∨ b13 2 = 0 ∨ b13 3 = 1 ∨ b13 0 = 3 ∨ b13 1 = 3 ∨ b13 2 = 1 ∨ b13 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb13
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b13 0 ∨ 0 = b13 1 ∨ 0 = b13 2 ∨ 1 = b13 3) ∨ (3 = b13 0 ∨ 3 = b13 1 ∨ 1 = b13 2 ∨ 0 = b13 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1640 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    : b14 0 = 0 ∨ b14 1 = 0 ∨ b14 2 = 0 ∨ b14 3 = 1 ∨ b14 0 = 3 ∨ b14 1 = 3 ∨ b14 2 = 1 ∨ b14 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb14
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b14 0 ∨ 0 = b14 1 ∨ 0 = b14 2 ∨ 1 = b14 3) ∨ (3 = b14 0 ∨ 3 = b14 1 ∨ 1 = b14 2 ∨ 0 = b14 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1641 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b15 : NatEdge) (hb15 : b15 ∈ H)
    : b15 0 = 0 ∨ b15 1 = 0 ∨ b15 2 = 0 ∨ b15 3 = 1 ∨ b15 0 = 3 ∨ b15 1 = 3 ∨ b15 2 = 1 ∨ b15 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb15
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b15 0 ∨ 0 = b15 1 ∨ 0 = b15 2 ∨ 1 = b15 3) ∨ (3 = b15 0 ∨ 3 = b15 1 ∨ 1 = b15 2 ∨ 0 = b15 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1642 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b18 : NatEdge) (hb18 : b18 ∈ H)
    : b18 0 = 0 ∨ b18 1 = 0 ∨ b18 2 = 0 ∨ b18 3 = 1 ∨ b18 0 = 3 ∨ b18 1 = 3 ∨ b18 2 = 1 ∨ b18 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb18
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b18 0 ∨ 0 = b18 1 ∨ 0 = b18 2 ∨ 1 = b18 3) ∨ (3 = b18 0 ∨ 3 = b18 1 ∨ 1 = b18 2 ∨ 0 = b18 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1643 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b19 : NatEdge) (hb19 : b19 ∈ H)
    : b19 0 = 0 ∨ b19 1 = 0 ∨ b19 2 = 0 ∨ b19 3 = 1 ∨ b19 0 = 3 ∨ b19 1 = 3 ∨ b19 2 = 1 ∨ b19 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb19
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b19 0 ∨ 0 = b19 1 ∨ 0 = b19 2 ∨ 1 = b19 3) ∨ (3 = b19 0 ∨ 3 = b19 1 ∨ 1 = b19 2 ∨ 0 = b19 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1644 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b20 : NatEdge) (hb20 : b20 ∈ H)
    : b20 0 = 0 ∨ b20 1 = 0 ∨ b20 2 = 0 ∨ b20 3 = 1 ∨ b20 0 = 3 ∨ b20 1 = 3 ∨ b20 2 = 1 ∨ b20 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb20
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b20 0 ∨ 0 = b20 1 ∨ 0 = b20 2 ∨ 1 = b20 3) ∨ (3 = b20 0 ∨ 3 = b20 1 ∨ 1 = b20 2 ∨ 0 = b20 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1645 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b21 : NatEdge) (hb21 : b21 ∈ H)
    : b21 0 = 0 ∨ b21 1 = 0 ∨ b21 2 = 0 ∨ b21 3 = 1 ∨ b21 0 = 3 ∨ b21 1 = 3 ∨ b21 2 = 1 ∨ b21 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb21
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b21 0 ∨ 0 = b21 1 ∨ 0 = b21 2 ∨ 1 = b21 3) ∨ (3 = b21 0 ∨ 3 = b21 1 ∨ 1 = b21 2 ∨ 0 = b21 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1646 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b22 : NatEdge) (hb22 : b22 ∈ H)
    : b22 0 = 0 ∨ b22 1 = 0 ∨ b22 2 = 0 ∨ b22 3 = 1 ∨ b22 0 = 3 ∨ b22 1 = 3 ∨ b22 2 = 1 ∨ b22 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb22
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b22 0 ∨ 0 = b22 1 ∨ 0 = b22 2 ∨ 1 = b22 3) ∨ (3 = b22 0 ∨ 3 = b22 1 ∨ 1 = b22 2 ∨ 0 = b22 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1647 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b23 0 = 0 ∨ b23 1 = 0 ∨ b23 2 = 0 ∨ b23 3 = 1 ∨ b23 0 = 3 ∨ b23 1 = 3 ∨ b23 2 = 1 ∨ b23 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb23
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b23 0 ∨ 0 = b23 1 ∨ 0 = b23 2 ∨ 1 = b23 3) ∨ (3 = b23 0 ∨ 3 = b23 1 ∨ 1 = b23 2 ∨ 0 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1648 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b29 : NatEdge) (hb29 : b29 ∈ H)
    : b29 0 = 0 ∨ b29 1 = 0 ∨ b29 2 = 0 ∨ b29 3 = 1 ∨ b29 0 = 3 ∨ b29 1 = 3 ∨ b29 2 = 1 ∨ b29 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb29
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b29 0 ∨ 0 = b29 1 ∨ 0 = b29 2 ∨ 1 = b29 3) ∨ (3 = b29 0 ∨ 3 = b29 1 ∨ 1 = b29 2 ∨ 0 = b29 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1649 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b30 : NatEdge) (hb30 : b30 ∈ H)
    : b30 0 = 0 ∨ b30 1 = 0 ∨ b30 2 = 0 ∨ b30 3 = 1 ∨ b30 0 = 3 ∨ b30 1 = 3 ∨ b30 2 = 1 ∨ b30 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb30
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b30 0 ∨ 0 = b30 1 ∨ 0 = b30 2 ∨ 1 = b30 3) ∨ (3 = b30 0 ∨ 3 = b30 1 ∨ 1 = b30 2 ∨ 0 = b30 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual1650 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 0 ∨ b0 1 = 0 ∨ b0 2 = 0 ∨ b0 3 = 1 ∨ b0 0 = 4 ∨ b0 1 = 4 ∨ b0 2 = 1 ∨ b0 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 4) hb0
  change (0 = 4 ∨ 0 = 4 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b0 0 ∨ 0 = b0 1 ∨ 0 = b0 2 ∨ 1 = b0 3) ∨ (4 = b0 0 ∨ 4 = b0 1 ∨ 1 = b0 2 ∨ 0 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))

#print axioms actual1650
end Ryser.WitnessCases.ResidualRow172_1225378239794.Cover
