module
public import Ryser.TwoResidualSets
public import Ryser.Theory.TemplateData
@[expose] public section
set_option maxRecDepth 8192
set_option maxHeartbeats 2000000
set_option linter.unusedVariables false
namespace Ryser.WitnessCases.ResidualRow172_1225378239794.Cover
open FiniteBox TwoResidualSets
theorem actual1801 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    : b12 0 = 1 ∨ b12 1 = 1 ∨ b12 2 = 0 ∨ b12 3 = 2 ∨ b14 0 = 1 ∨ b14 1 = 1 ∨ b14 2 = 0 ∨ b14 3 = 2 ∨ b12 0 = b14 0 ∨ b12 1 = b14 1 ∨ b12 2 = b14 2 ∨ b12 3 = b14 3 := by
  have ht := no_three_hits noThree (hF 1) hb12 hb14
  change (1 = b12 0 ∨ 1 = b12 1 ∨ 0 = b12 2 ∨ 2 = b12 3) ∨ (1 = b14 0 ∨ 1 = b14 1 ∨ 0 = b14 2 ∨ 2 = b14 3) ∨ (b12 0 = b14 0 ∨ b12 1 = b14 1 ∨ b12 2 = b14 2 ∨ b12 3 = b14 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1802 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    (b22 : NatEdge) (hb22 : b22 ∈ H)
    : b12 0 = 1 ∨ b12 1 = 1 ∨ b12 2 = 0 ∨ b12 3 = 2 ∨ b22 0 = 1 ∨ b22 1 = 1 ∨ b22 2 = 0 ∨ b22 3 = 2 ∨ b12 0 = b22 0 ∨ b12 1 = b22 1 ∨ b12 2 = b22 2 ∨ b12 3 = b22 3 := by
  have ht := no_three_hits noThree (hF 1) hb12 hb22
  change (1 = b12 0 ∨ 1 = b12 1 ∨ 0 = b12 2 ∨ 2 = b12 3) ∨ (1 = b22 0 ∨ 1 = b22 1 ∨ 0 = b22 2 ∨ 2 = b22 3) ∨ (b12 0 = b22 0 ∨ b12 1 = b22 1 ∨ b12 2 = b22 2 ∨ b12 3 = b22 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1803 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b12 0 = 1 ∨ b12 1 = 1 ∨ b12 2 = 0 ∨ b12 3 = 2 ∨ b23 0 = 1 ∨ b23 1 = 1 ∨ b23 2 = 0 ∨ b23 3 = 2 ∨ b12 0 = b23 0 ∨ b12 1 = b23 1 ∨ b12 2 = b23 2 ∨ b12 3 = b23 3 := by
  have ht := no_three_hits noThree (hF 1) hb12 hb23
  change (1 = b12 0 ∨ 1 = b12 1 ∨ 0 = b12 2 ∨ 2 = b12 3) ∨ (1 = b23 0 ∨ 1 = b23 1 ∨ 0 = b23 2 ∨ 2 = b23 3) ∨ (b12 0 = b23 0 ∨ b12 1 = b23 1 ∨ b12 2 = b23 2 ∨ b12 3 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1804 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    (b30 : NatEdge) (hb30 : b30 ∈ H)
    : b12 0 = 1 ∨ b12 1 = 1 ∨ b12 2 = 0 ∨ b12 3 = 2 ∨ b30 0 = 1 ∨ b30 1 = 1 ∨ b30 2 = 0 ∨ b30 3 = 2 ∨ b12 0 = b30 0 ∨ b12 1 = b30 1 ∨ b12 2 = b30 2 ∨ b12 3 = b30 3 := by
  have ht := no_three_hits noThree (hF 1) hb12 hb30
  change (1 = b12 0 ∨ 1 = b12 1 ∨ 0 = b12 2 ∨ 2 = b12 3) ∨ (1 = b30 0 ∨ 1 = b30 1 ∨ 0 = b30 2 ∨ 2 = b30 3) ∨ (b12 0 = b30 0 ∨ b12 1 = b30 1 ∨ b12 2 = b30 2 ∨ b12 3 = b30 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1805 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    : b13 0 = 1 ∨ b13 1 = 1 ∨ b13 2 = 0 ∨ b13 3 = 2 ∨ b14 0 = 1 ∨ b14 1 = 1 ∨ b14 2 = 0 ∨ b14 3 = 2 ∨ b13 0 = b14 0 ∨ b13 1 = b14 1 ∨ b13 2 = b14 2 ∨ b13 3 = b14 3 := by
  have ht := no_three_hits noThree (hF 1) hb13 hb14
  change (1 = b13 0 ∨ 1 = b13 1 ∨ 0 = b13 2 ∨ 2 = b13 3) ∨ (1 = b14 0 ∨ 1 = b14 1 ∨ 0 = b14 2 ∨ 2 = b14 3) ∨ (b13 0 = b14 0 ∨ b13 1 = b14 1 ∨ b13 2 = b14 2 ∨ b13 3 = b14 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1806 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    (b18 : NatEdge) (hb18 : b18 ∈ H)
    : b13 0 = 1 ∨ b13 1 = 1 ∨ b13 2 = 0 ∨ b13 3 = 2 ∨ b18 0 = 1 ∨ b18 1 = 1 ∨ b18 2 = 0 ∨ b18 3 = 2 ∨ b13 0 = b18 0 ∨ b13 1 = b18 1 ∨ b13 2 = b18 2 ∨ b13 3 = b18 3 := by
  have ht := no_three_hits noThree (hF 1) hb13 hb18
  change (1 = b13 0 ∨ 1 = b13 1 ∨ 0 = b13 2 ∨ 2 = b13 3) ∨ (1 = b18 0 ∨ 1 = b18 1 ∨ 0 = b18 2 ∨ 2 = b18 3) ∨ (b13 0 = b18 0 ∨ b13 1 = b18 1 ∨ b13 2 = b18 2 ∨ b13 3 = b18 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1807 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    (b22 : NatEdge) (hb22 : b22 ∈ H)
    : b13 0 = 1 ∨ b13 1 = 1 ∨ b13 2 = 0 ∨ b13 3 = 2 ∨ b22 0 = 1 ∨ b22 1 = 1 ∨ b22 2 = 0 ∨ b22 3 = 2 ∨ b13 0 = b22 0 ∨ b13 1 = b22 1 ∨ b13 2 = b22 2 ∨ b13 3 = b22 3 := by
  have ht := no_three_hits noThree (hF 1) hb13 hb22
  change (1 = b13 0 ∨ 1 = b13 1 ∨ 0 = b13 2 ∨ 2 = b13 3) ∨ (1 = b22 0 ∨ 1 = b22 1 ∨ 0 = b22 2 ∨ 2 = b22 3) ∨ (b13 0 = b22 0 ∨ b13 1 = b22 1 ∨ b13 2 = b22 2 ∨ b13 3 = b22 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1808 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b13 0 = 1 ∨ b13 1 = 1 ∨ b13 2 = 0 ∨ b13 3 = 2 ∨ b23 0 = 1 ∨ b23 1 = 1 ∨ b23 2 = 0 ∨ b23 3 = 2 ∨ b13 0 = b23 0 ∨ b13 1 = b23 1 ∨ b13 2 = b23 2 ∨ b13 3 = b23 3 := by
  have ht := no_three_hits noThree (hF 1) hb13 hb23
  change (1 = b13 0 ∨ 1 = b13 1 ∨ 0 = b13 2 ∨ 2 = b13 3) ∨ (1 = b23 0 ∨ 1 = b23 1 ∨ 0 = b23 2 ∨ 2 = b23 3) ∨ (b13 0 = b23 0 ∨ b13 1 = b23 1 ∨ b13 2 = b23 2 ∨ b13 3 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1809 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    (b30 : NatEdge) (hb30 : b30 ∈ H)
    : b13 0 = 1 ∨ b13 1 = 1 ∨ b13 2 = 0 ∨ b13 3 = 2 ∨ b30 0 = 1 ∨ b30 1 = 1 ∨ b30 2 = 0 ∨ b30 3 = 2 ∨ b13 0 = b30 0 ∨ b13 1 = b30 1 ∨ b13 2 = b30 2 ∨ b13 3 = b30 3 := by
  have ht := no_three_hits noThree (hF 1) hb13 hb30
  change (1 = b13 0 ∨ 1 = b13 1 ∨ 0 = b13 2 ∨ 2 = b13 3) ∨ (1 = b30 0 ∨ 1 = b30 1 ∨ 0 = b30 2 ∨ 2 = b30 3) ∨ (b13 0 = b30 0 ∨ b13 1 = b30 1 ∨ b13 2 = b30 2 ∨ b13 3 = b30 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1810 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    (b18 : NatEdge) (hb18 : b18 ∈ H)
    : b14 0 = 1 ∨ b14 1 = 1 ∨ b14 2 = 0 ∨ b14 3 = 2 ∨ b18 0 = 1 ∨ b18 1 = 1 ∨ b18 2 = 0 ∨ b18 3 = 2 ∨ b14 0 = b18 0 ∨ b14 1 = b18 1 ∨ b14 2 = b18 2 ∨ b14 3 = b18 3 := by
  have ht := no_three_hits noThree (hF 1) hb14 hb18
  change (1 = b14 0 ∨ 1 = b14 1 ∨ 0 = b14 2 ∨ 2 = b14 3) ∨ (1 = b18 0 ∨ 1 = b18 1 ∨ 0 = b18 2 ∨ 2 = b18 3) ∨ (b14 0 = b18 0 ∨ b14 1 = b18 1 ∨ b14 2 = b18 2 ∨ b14 3 = b18 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1811 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    (b19 : NatEdge) (hb19 : b19 ∈ H)
    : b14 0 = 1 ∨ b14 1 = 1 ∨ b14 2 = 0 ∨ b14 3 = 2 ∨ b19 0 = 1 ∨ b19 1 = 1 ∨ b19 2 = 0 ∨ b19 3 = 2 ∨ b14 0 = b19 0 ∨ b14 1 = b19 1 ∨ b14 2 = b19 2 ∨ b14 3 = b19 3 := by
  have ht := no_three_hits noThree (hF 1) hb14 hb19
  change (1 = b14 0 ∨ 1 = b14 1 ∨ 0 = b14 2 ∨ 2 = b14 3) ∨ (1 = b19 0 ∨ 1 = b19 1 ∨ 0 = b19 2 ∨ 2 = b19 3) ∨ (b14 0 = b19 0 ∨ b14 1 = b19 1 ∨ b14 2 = b19 2 ∨ b14 3 = b19 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1812 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    (b21 : NatEdge) (hb21 : b21 ∈ H)
    : b14 0 = 1 ∨ b14 1 = 1 ∨ b14 2 = 0 ∨ b14 3 = 2 ∨ b21 0 = 1 ∨ b21 1 = 1 ∨ b21 2 = 0 ∨ b21 3 = 2 ∨ b14 0 = b21 0 ∨ b14 1 = b21 1 ∨ b14 2 = b21 2 ∨ b14 3 = b21 3 := by
  have ht := no_three_hits noThree (hF 1) hb14 hb21
  change (1 = b14 0 ∨ 1 = b14 1 ∨ 0 = b14 2 ∨ 2 = b14 3) ∨ (1 = b21 0 ∨ 1 = b21 1 ∨ 0 = b21 2 ∨ 2 = b21 3) ∨ (b14 0 = b21 0 ∨ b14 1 = b21 1 ∨ b14 2 = b21 2 ∨ b14 3 = b21 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1813 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    (b30 : NatEdge) (hb30 : b30 ∈ H)
    : b14 0 = 1 ∨ b14 1 = 1 ∨ b14 2 = 0 ∨ b14 3 = 2 ∨ b30 0 = 1 ∨ b30 1 = 1 ∨ b30 2 = 0 ∨ b30 3 = 2 ∨ b14 0 = b30 0 ∨ b14 1 = b30 1 ∨ b14 2 = b30 2 ∨ b14 3 = b30 3 := by
  have ht := no_three_hits noThree (hF 1) hb14 hb30
  change (1 = b14 0 ∨ 1 = b14 1 ∨ 0 = b14 2 ∨ 2 = b14 3) ∨ (1 = b30 0 ∨ 1 = b30 1 ∨ 0 = b30 2 ∨ 2 = b30 3) ∨ (b14 0 = b30 0 ∨ b14 1 = b30 1 ∨ b14 2 = b30 2 ∨ b14 3 = b30 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1814 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b15 : NatEdge) (hb15 : b15 ∈ H)
    (b18 : NatEdge) (hb18 : b18 ∈ H)
    : b15 0 = 1 ∨ b15 1 = 1 ∨ b15 2 = 0 ∨ b15 3 = 2 ∨ b18 0 = 1 ∨ b18 1 = 1 ∨ b18 2 = 0 ∨ b18 3 = 2 ∨ b15 0 = b18 0 ∨ b15 1 = b18 1 ∨ b15 2 = b18 2 ∨ b15 3 = b18 3 := by
  have ht := no_three_hits noThree (hF 1) hb15 hb18
  change (1 = b15 0 ∨ 1 = b15 1 ∨ 0 = b15 2 ∨ 2 = b15 3) ∨ (1 = b18 0 ∨ 1 = b18 1 ∨ 0 = b18 2 ∨ 2 = b18 3) ∨ (b15 0 = b18 0 ∨ b15 1 = b18 1 ∨ b15 2 = b18 2 ∨ b15 3 = b18 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1815 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 172 k ∈ H)
    (b15 : NatEdge) (hb15 : b15 ∈ H)
    (b19 : NatEdge) (hb19 : b19 ∈ H)
    : b15 0 = 1 ∨ b15 1 = 1 ∨ b15 2 = 0 ∨ b15 3 = 2 ∨ b19 0 = 1 ∨ b19 1 = 1 ∨ b19 2 = 0 ∨ b19 3 = 2 ∨ b15 0 = b19 0 ∨ b15 1 = b19 1 ∨ b15 2 = b19 2 ∨ b15 3 = b19 3 := by
  have ht := no_three_hits noThree (hF 1) hb15 hb19
  change (1 = b15 0 ∨ 1 = b15 1 ∨ 0 = b15 2 ∨ 2 = b15 3) ∨ (1 = b19 0 ∨ 1 = b19 1 ∨ 0 = b19 2 ∨ 2 = b19 3) ∨ (b15 0 = b19 0 ∨ b15 1 = b19 1 ∨ b15 2 = b19 2 ∨ b15 3 = b19 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))

#print axioms actual1815
end Ryser.WitnessCases.ResidualRow172_1225378239794.Cover
