module
public import Ryser.TwoResidualSets
public import Ryser.Theory.TemplateData
@[expose] public section
set_option maxRecDepth 8192
set_option maxHeartbeats 2000000
set_option linter.unusedVariables false
namespace Ryser.WitnessCases.Row119_113001661283.Cover
open FiniteBox TwoResidualSets
theorem actual523 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    : b12 0 = 2 ∨ b12 1 = 2 ∨ b12 2 = 0 ∨ b12 3 = 1 ∨ b12 0 = 6 ∨ b12 1 = 6 ∨ b12 2 = 1 ∨ b12 3 = 2 := by
  have ht := no_three_hits noThree (hF 2) (hF 6) hb12
  change (2 = 6 ∨ 2 = 6 ∨ 0 = 1 ∨ 1 = 2) ∨ (2 = b12 0 ∨ 2 = b12 1 ∨ 0 = b12 2 ∨ 1 = b12 3) ∨ (6 = b12 0 ∨ 6 = b12 1 ∨ 1 = b12 2 ∨ 2 = b12 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 6) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 6) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual524 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    : b14 0 = 2 ∨ b14 1 = 2 ∨ b14 2 = 0 ∨ b14 3 = 1 ∨ b14 0 = 6 ∨ b14 1 = 6 ∨ b14 2 = 1 ∨ b14 3 = 2 := by
  have ht := no_three_hits noThree (hF 2) (hF 6) hb14
  change (2 = 6 ∨ 2 = 6 ∨ 0 = 1 ∨ 1 = 2) ∨ (2 = b14 0 ∨ 2 = b14 1 ∨ 0 = b14 2 ∨ 1 = b14 3) ∨ (6 = b14 0 ∨ 6 = b14 1 ∨ 1 = b14 2 ∨ 2 = b14 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 6) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 6) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual525 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 3 ∨ b0 1 = 3 ∨ b0 2 = 1 ∨ b0 3 = 1 ∨ b0 0 = 4 ∨ b0 1 = 4 ∨ b0 2 = 0 ∨ b0 3 = 2 := by
  have ht := no_three_hits noThree (hF 3) (hF 4) hb0
  change (3 = 4 ∨ 3 = 4 ∨ 1 = 0 ∨ 1 = 2) ∨ (3 = b0 0 ∨ 3 = b0 1 ∨ 1 = b0 2 ∨ 1 = b0 3) ∨ (4 = b0 0 ∨ 4 = b0 1 ∨ 0 = b0 2 ∨ 2 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual526 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b1 : NatEdge) (hb1 : b1 ∈ H)
    : b1 0 = 3 ∨ b1 1 = 3 ∨ b1 2 = 1 ∨ b1 3 = 1 ∨ b1 0 = 4 ∨ b1 1 = 4 ∨ b1 2 = 0 ∨ b1 3 = 2 := by
  have ht := no_three_hits noThree (hF 3) (hF 4) hb1
  change (3 = 4 ∨ 3 = 4 ∨ 1 = 0 ∨ 1 = 2) ∨ (3 = b1 0 ∨ 3 = b1 1 ∨ 1 = b1 2 ∨ 1 = b1 3) ∨ (4 = b1 0 ∨ 4 = b1 1 ∨ 0 = b1 2 ∨ 2 = b1 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual527 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    : b2 0 = 3 ∨ b2 1 = 3 ∨ b2 2 = 1 ∨ b2 3 = 1 ∨ b2 0 = 4 ∨ b2 1 = 4 ∨ b2 2 = 0 ∨ b2 3 = 2 := by
  have ht := no_three_hits noThree (hF 3) (hF 4) hb2
  change (3 = 4 ∨ 3 = 4 ∨ 1 = 0 ∨ 1 = 2) ∨ (3 = b2 0 ∨ 3 = b2 1 ∨ 1 = b2 2 ∨ 1 = b2 3) ∨ (4 = b2 0 ∨ 4 = b2 1 ∨ 0 = b2 2 ∨ 2 = b2 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual528 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b3 : NatEdge) (hb3 : b3 ∈ H)
    : b3 0 = 3 ∨ b3 1 = 3 ∨ b3 2 = 1 ∨ b3 3 = 1 ∨ b3 0 = 4 ∨ b3 1 = 4 ∨ b3 2 = 0 ∨ b3 3 = 2 := by
  have ht := no_three_hits noThree (hF 3) (hF 4) hb3
  change (3 = 4 ∨ 3 = 4 ∨ 1 = 0 ∨ 1 = 2) ∨ (3 = b3 0 ∨ 3 = b3 1 ∨ 1 = b3 2 ∨ 1 = b3 3) ∨ (4 = b3 0 ∨ 4 = b3 1 ∨ 0 = b3 2 ∨ 2 = b3 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual529 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b4 : NatEdge) (hb4 : b4 ∈ H)
    : b4 0 = 3 ∨ b4 1 = 3 ∨ b4 2 = 1 ∨ b4 3 = 1 ∨ b4 0 = 4 ∨ b4 1 = 4 ∨ b4 2 = 0 ∨ b4 3 = 2 := by
  have ht := no_three_hits noThree (hF 3) (hF 4) hb4
  change (3 = 4 ∨ 3 = 4 ∨ 1 = 0 ∨ 1 = 2) ∨ (3 = b4 0 ∨ 3 = b4 1 ∨ 1 = b4 2 ∨ 1 = b4 3) ∨ (4 = b4 0 ∨ 4 = b4 1 ∨ 0 = b4 2 ∨ 2 = b4 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual530 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    : b6 0 = 3 ∨ b6 1 = 3 ∨ b6 2 = 1 ∨ b6 3 = 1 ∨ b6 0 = 4 ∨ b6 1 = 4 ∨ b6 2 = 0 ∨ b6 3 = 2 := by
  have ht := no_three_hits noThree (hF 3) (hF 4) hb6
  change (3 = 4 ∨ 3 = 4 ∨ 1 = 0 ∨ 1 = 2) ∨ (3 = b6 0 ∨ 3 = b6 1 ∨ 1 = b6 2 ∨ 1 = b6 3) ∨ (4 = b6 0 ∨ 4 = b6 1 ∨ 0 = b6 2 ∨ 2 = b6 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual531 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b7 : NatEdge) (hb7 : b7 ∈ H)
    : b7 0 = 3 ∨ b7 1 = 3 ∨ b7 2 = 1 ∨ b7 3 = 1 ∨ b7 0 = 4 ∨ b7 1 = 4 ∨ b7 2 = 0 ∨ b7 3 = 2 := by
  have ht := no_three_hits noThree (hF 3) (hF 4) hb7
  change (3 = 4 ∨ 3 = 4 ∨ 1 = 0 ∨ 1 = 2) ∨ (3 = b7 0 ∨ 3 = b7 1 ∨ 1 = b7 2 ∨ 1 = b7 3) ∨ (4 = b7 0 ∨ 4 = b7 1 ∨ 0 = b7 2 ∨ 2 = b7 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual532 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    : b12 0 = 3 ∨ b12 1 = 3 ∨ b12 2 = 1 ∨ b12 3 = 1 ∨ b12 0 = 4 ∨ b12 1 = 4 ∨ b12 2 = 0 ∨ b12 3 = 2 := by
  have ht := no_three_hits noThree (hF 3) (hF 4) hb12
  change (3 = 4 ∨ 3 = 4 ∨ 1 = 0 ∨ 1 = 2) ∨ (3 = b12 0 ∨ 3 = b12 1 ∨ 1 = b12 2 ∨ 1 = b12 3) ∨ (4 = b12 0 ∨ 4 = b12 1 ∨ 0 = b12 2 ∨ 2 = b12 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual533 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    : b14 0 = 3 ∨ b14 1 = 3 ∨ b14 2 = 1 ∨ b14 3 = 1 ∨ b14 0 = 4 ∨ b14 1 = 4 ∨ b14 2 = 0 ∨ b14 3 = 2 := by
  have ht := no_three_hits noThree (hF 3) (hF 4) hb14
  change (3 = 4 ∨ 3 = 4 ∨ 1 = 0 ∨ 1 = 2) ∨ (3 = b14 0 ∨ 3 = b14 1 ∨ 1 = b14 2 ∨ 1 = b14 3) ∨ (4 = b14 0 ∨ 4 = b14 1 ∨ 0 = b14 2 ∨ 2 = b14 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (3 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual534 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    (b1 : NatEdge) (hb1 : b1 ∈ H)
    : b0 0 = 3 ∨ b0 1 = 3 ∨ b0 2 = 1 ∨ b0 3 = 1 ∨ b1 0 = 3 ∨ b1 1 = 3 ∨ b1 2 = 1 ∨ b1 3 = 1 ∨ b0 0 = b1 0 ∨ b0 1 = b1 1 ∨ b0 2 = b1 2 ∨ b0 3 = b1 3 := by
  have ht := no_three_hits noThree (hF 3) hb0 hb1
  change (3 = b0 0 ∨ 3 = b0 1 ∨ 1 = b0 2 ∨ 1 = b0 3) ∨ (3 = b1 0 ∨ 3 = b1 1 ∨ 1 = b1 2 ∨ 1 = b1 3) ∨ (b0 0 = b1 0 ∨ b0 1 = b1 1 ∨ b0 2 = b1 2 ∨ b0 3 = b1 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual535 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    : b0 0 = 3 ∨ b0 1 = 3 ∨ b0 2 = 1 ∨ b0 3 = 1 ∨ b2 0 = 3 ∨ b2 1 = 3 ∨ b2 2 = 1 ∨ b2 3 = 1 ∨ b0 0 = b2 0 ∨ b0 1 = b2 1 ∨ b0 2 = b2 2 ∨ b0 3 = b2 3 := by
  have ht := no_three_hits noThree (hF 3) hb0 hb2
  change (3 = b0 0 ∨ 3 = b0 1 ∨ 1 = b0 2 ∨ 1 = b0 3) ∨ (3 = b2 0 ∨ 3 = b2 1 ∨ 1 = b2 2 ∨ 1 = b2 3) ∨ (b0 0 = b2 0 ∨ b0 1 = b2 1 ∨ b0 2 = b2 2 ∨ b0 3 = b2 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual536 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    (b3 : NatEdge) (hb3 : b3 ∈ H)
    : b0 0 = 3 ∨ b0 1 = 3 ∨ b0 2 = 1 ∨ b0 3 = 1 ∨ b3 0 = 3 ∨ b3 1 = 3 ∨ b3 2 = 1 ∨ b3 3 = 1 ∨ b0 0 = b3 0 ∨ b0 1 = b3 1 ∨ b0 2 = b3 2 ∨ b0 3 = b3 3 := by
  have ht := no_three_hits noThree (hF 3) hb0 hb3
  change (3 = b0 0 ∨ 3 = b0 1 ∨ 1 = b0 2 ∨ 1 = b0 3) ∨ (3 = b3 0 ∨ 3 = b3 1 ∨ 1 = b3 2 ∨ 1 = b3 3) ∨ (b0 0 = b3 0 ∨ b0 1 = b3 1 ∨ b0 2 = b3 2 ∨ b0 3 = b3 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual537 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 119 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    (b4 : NatEdge) (hb4 : b4 ∈ H)
    : b0 0 = 3 ∨ b0 1 = 3 ∨ b0 2 = 1 ∨ b0 3 = 1 ∨ b4 0 = 3 ∨ b4 1 = 3 ∨ b4 2 = 1 ∨ b4 3 = 1 ∨ b0 0 = b4 0 ∨ b0 1 = b4 1 ∨ b0 2 = b4 2 ∨ b0 3 = b4 3 := by
  have ht := no_three_hits noThree (hF 3) hb0 hb4
  change (3 = b0 0 ∨ 3 = b0 1 ∨ 1 = b0 2 ∨ 1 = b0 3) ∨ (3 = b4 0 ∨ 3 = b4 1 ∨ 1 = b4 2 ∨ 1 = b4 3) ∨ (b0 0 = b4 0 ∨ b0 1 = b4 1 ∨ b0 2 = b4 2 ∨ b0 3 = b4 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))

#print axioms actual537
end Ryser.WitnessCases.Row119_113001661283.Cover
