module
public import Ryser.TwoResidualSets
public import Ryser.Theory.TemplateData
@[expose] public section
set_option maxRecDepth 8192
set_option maxHeartbeats 2000000
set_option linter.unusedVariables false
namespace Ryser.WitnessCases.Row175_113101450771.Cover
open FiniteBox TwoResidualSets
theorem actual127 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 0 ∨ b0 1 = 0 ∨ b0 2 = 0 ∨ b0 3 = 1 ∨ b0 0 = 3 ∨ b0 1 = 3 ∨ b0 2 = 1 ∨ b0 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb0
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b0 0 ∨ 0 = b0 1 ∨ 0 = b0 2 ∨ 1 = b0 3) ∨ (3 = b0 0 ∨ 3 = b0 1 ∨ 1 = b0 2 ∨ 0 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual128 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b10 : NatEdge) (hb10 : b10 ∈ H)
    : b10 0 = 0 ∨ b10 1 = 0 ∨ b10 2 = 0 ∨ b10 3 = 1 ∨ b10 0 = 3 ∨ b10 1 = 3 ∨ b10 2 = 1 ∨ b10 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb10
  change (0 = 3 ∨ 0 = 3 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b10 0 ∨ 0 = b10 1 ∨ 0 = b10 2 ∨ 1 = b10 3) ∨ (3 = b10 0 ∨ 3 = b10 1 ∨ 1 = b10 2 ∨ 0 = b10 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual129 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 0 ∨ b0 1 = 0 ∨ b0 2 = 0 ∨ b0 3 = 1 ∨ b0 0 = 4 ∨ b0 1 = 4 ∨ b0 2 = 1 ∨ b0 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 4) hb0
  change (0 = 4 ∨ 0 = 4 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b0 0 ∨ 0 = b0 1 ∨ 0 = b0 2 ∨ 1 = b0 3) ∨ (4 = b0 0 ∨ 4 = b0 1 ∨ 1 = b0 2 ∨ 0 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual130 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b10 : NatEdge) (hb10 : b10 ∈ H)
    : b10 0 = 0 ∨ b10 1 = 0 ∨ b10 2 = 0 ∨ b10 3 = 1 ∨ b10 0 = 4 ∨ b10 1 = 4 ∨ b10 2 = 1 ∨ b10 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 4) hb10
  change (0 = 4 ∨ 0 = 4 ∨ 0 = 1 ∨ 1 = 0) ∨ (0 = b10 0 ∨ 0 = b10 1 ∨ 0 = b10 2 ∨ 1 = b10 3) ∨ (4 = b10 0 ∨ 4 = b10 1 ∨ 1 = b10 2 ∨ 0 = b10 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual131 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 0 ∨ b0 1 = 0 ∨ b0 2 = 0 ∨ b0 3 = 1 ∨ b0 0 = 5 ∨ b0 1 = 5 ∨ b0 2 = 2 ∨ b0 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 5) hb0
  change (0 = 5 ∨ 0 = 5 ∨ 0 = 2 ∨ 1 = 0) ∨ (0 = b0 0 ∨ 0 = b0 1 ∨ 0 = b0 2 ∨ 1 = b0 3) ∨ (5 = b0 0 ∨ 5 = b0 1 ∨ 2 = b0 2 ∨ 0 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual132 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b10 : NatEdge) (hb10 : b10 ∈ H)
    : b10 0 = 0 ∨ b10 1 = 0 ∨ b10 2 = 0 ∨ b10 3 = 1 ∨ b10 0 = 5 ∨ b10 1 = 5 ∨ b10 2 = 2 ∨ b10 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 5) hb10
  change (0 = 5 ∨ 0 = 5 ∨ 0 = 2 ∨ 1 = 0) ∨ (0 = b10 0 ∨ 0 = b10 1 ∨ 0 = b10 2 ∨ 1 = b10 3) ∨ (5 = b10 0 ∨ 5 = b10 1 ∨ 2 = b10 2 ∨ 0 = b10 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual133 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b11 : NatEdge) (hb11 : b11 ∈ H)
    : b11 0 = 0 ∨ b11 1 = 0 ∨ b11 2 = 0 ∨ b11 3 = 1 ∨ b11 0 = 5 ∨ b11 1 = 5 ∨ b11 2 = 2 ∨ b11 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 5) hb11
  change (0 = 5 ∨ 0 = 5 ∨ 0 = 2 ∨ 1 = 0) ∨ (0 = b11 0 ∨ 0 = b11 1 ∨ 0 = b11 2 ∨ 1 = b11 3) ∨ (5 = b11 0 ∨ 5 = b11 1 ∨ 2 = b11 2 ∨ 0 = b11 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual134 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 0 ∨ b0 1 = 0 ∨ b0 2 = 0 ∨ b0 3 = 1 ∨ b0 0 = 6 ∨ b0 1 = 6 ∨ b0 2 = 2 ∨ b0 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 6) hb0
  change (0 = 6 ∨ 0 = 6 ∨ 0 = 2 ∨ 1 = 0) ∨ (0 = b0 0 ∨ 0 = b0 1 ∨ 0 = b0 2 ∨ 1 = b0 3) ∨ (6 = b0 0 ∨ 6 = b0 1 ∨ 2 = b0 2 ∨ 0 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 6) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 6) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual135 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b10 : NatEdge) (hb10 : b10 ∈ H)
    : b10 0 = 0 ∨ b10 1 = 0 ∨ b10 2 = 0 ∨ b10 3 = 1 ∨ b10 0 = 6 ∨ b10 1 = 6 ∨ b10 2 = 2 ∨ b10 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 6) hb10
  change (0 = 6 ∨ 0 = 6 ∨ 0 = 2 ∨ 1 = 0) ∨ (0 = b10 0 ∨ 0 = b10 1 ∨ 0 = b10 2 ∨ 1 = b10 3) ∨ (6 = b10 0 ∨ 6 = b10 1 ∨ 2 = b10 2 ∨ 0 = b10 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 6) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 6) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual136 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b11 : NatEdge) (hb11 : b11 ∈ H)
    : b11 0 = 0 ∨ b11 1 = 0 ∨ b11 2 = 0 ∨ b11 3 = 1 ∨ b11 0 = 6 ∨ b11 1 = 6 ∨ b11 2 = 2 ∨ b11 3 = 0 := by
  have ht := no_three_hits noThree (hF 0) (hF 6) hb11
  change (0 = 6 ∨ 0 = 6 ∨ 0 = 2 ∨ 1 = 0) ∨ (0 = b11 0 ∨ 0 = b11 1 ∨ 0 = b11 2 ∨ 1 = b11 3) ∨ (6 = b11 0 ∨ 6 = b11 1 ∨ 2 = b11 2 ∨ 0 = b11 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 6) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 6) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual137 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    (b10 : NatEdge) (hb10 : b10 ∈ H)
    : b0 0 = 0 ∨ b0 1 = 0 ∨ b0 2 = 0 ∨ b0 3 = 1 ∨ b10 0 = 0 ∨ b10 1 = 0 ∨ b10 2 = 0 ∨ b10 3 = 1 ∨ b0 0 = b10 0 ∨ b0 1 = b10 1 ∨ b0 2 = b10 2 ∨ b0 3 = b10 3 := by
  have ht := no_three_hits noThree (hF 0) hb0 hb10
  change (0 = b0 0 ∨ 0 = b0 1 ∨ 0 = b0 2 ∨ 1 = b0 3) ∨ (0 = b10 0 ∨ 0 = b10 1 ∨ 0 = b10 2 ∨ 1 = b10 3) ∨ (b0 0 = b10 0 ∨ b0 1 = b10 1 ∨ b0 2 = b10 2 ∨ b0 3 = b10 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual138 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b10 : NatEdge) (hb10 : b10 ∈ H)
    (b11 : NatEdge) (hb11 : b11 ∈ H)
    : b10 0 = 0 ∨ b10 1 = 0 ∨ b10 2 = 0 ∨ b10 3 = 1 ∨ b11 0 = 0 ∨ b11 1 = 0 ∨ b11 2 = 0 ∨ b11 3 = 1 ∨ b10 0 = b11 0 ∨ b10 1 = b11 1 ∨ b10 2 = b11 2 ∨ b10 3 = b11 3 := by
  have ht := no_three_hits noThree (hF 0) hb10 hb11
  change (0 = b10 0 ∨ 0 = b10 1 ∨ 0 = b10 2 ∨ 1 = b10 3) ∨ (0 = b11 0 ∨ 0 = b11 1 ∨ 0 = b11 2 ∨ 1 = b11 3) ∨ (b10 0 = b11 0 ∨ b10 1 = b11 1 ∨ b10 2 = b11 2 ∨ b10 3 = b11 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual139 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 1 ∨ b0 1 = 1 ∨ b0 2 = 0 ∨ b0 3 = 2 ∨ b0 0 = 3 ∨ b0 1 = 3 ∨ b0 2 = 1 ∨ b0 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 3) hb0
  change (1 = 3 ∨ 1 = 3 ∨ 0 = 1 ∨ 2 = 0) ∨ (1 = b0 0 ∨ 1 = b0 1 ∨ 0 = b0 2 ∨ 2 = b0 3) ∨ (3 = b0 0 ∨ 3 = b0 1 ∨ 1 = b0 2 ∨ 0 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual140 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b10 : NatEdge) (hb10 : b10 ∈ H)
    : b10 0 = 1 ∨ b10 1 = 1 ∨ b10 2 = 0 ∨ b10 3 = 2 ∨ b10 0 = 3 ∨ b10 1 = 3 ∨ b10 2 = 1 ∨ b10 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 3) hb10
  change (1 = 3 ∨ 1 = 3 ∨ 0 = 1 ∨ 2 = 0) ∨ (1 = b10 0 ∨ 1 = b10 1 ∨ 0 = b10 2 ∨ 2 = b10 3) ∨ (3 = b10 0 ∨ 3 = b10 1 ∨ 1 = b10 2 ∨ 0 = b10 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual141 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 175 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 1 ∨ b0 1 = 1 ∨ b0 2 = 0 ∨ b0 3 = 2 ∨ b0 0 = 4 ∨ b0 1 = 4 ∨ b0 2 = 1 ∨ b0 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 4) hb0
  change (1 = 4 ∨ 1 = 4 ∨ 0 = 1 ∨ 2 = 0) ∨ (1 = b0 0 ∨ 1 = b0 1 ∨ 0 = b0 2 ∨ 2 = b0 3) ∨ (4 = b0 0 ∨ 4 = b0 1 ∨ 1 = b0 2 ∨ 0 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))

#print axioms actual141
end Ryser.WitnessCases.Row175_113101450771.Cover
