module
public import Ryser.TwoResidualSets
public import Ryser.Theory.TemplateData
@[expose] public section
set_option maxRecDepth 8192
set_option maxHeartbeats 2000000
set_option linter.unusedVariables false
namespace Ryser.WitnessCases.Row116_105257974128.Cover
open FiniteBox TwoResidualSets
theorem actual368 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b11 : NatEdge) (hb11 : b11 ∈ H)
    : b11 0 = 1 ∨ b11 1 = 1 ∨ b11 2 = 1 ∨ b11 3 = 0 ∨ b11 0 = 4 ∨ b11 1 = 4 ∨ b11 2 = 0 ∨ b11 3 = 2 := by
  have ht := no_three_hits noThree (hF 1) (hF 4) hb11
  change (1 = 4 ∨ 1 = 4 ∨ 1 = 0 ∨ 0 = 2) ∨ (1 = b11 0 ∨ 1 = b11 1 ∨ 1 = b11 2 ∨ 0 = b11 3) ∨ (4 = b11 0 ∨ 4 = b11 1 ∨ 0 = b11 2 ∨ 2 = b11 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual369 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 1 ∨ b0 1 = 1 ∨ b0 2 = 1 ∨ b0 3 = 0 ∨ b0 0 = 5 ∨ b0 1 = 5 ∨ b0 2 = 0 ∨ b0 3 = 2 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb0
  change (1 = 5 ∨ 1 = 5 ∨ 1 = 0 ∨ 0 = 2) ∨ (1 = b0 0 ∨ 1 = b0 1 ∨ 1 = b0 2 ∨ 0 = b0 3) ∨ (5 = b0 0 ∨ 5 = b0 1 ∨ 0 = b0 2 ∨ 2 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual370 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b1 : NatEdge) (hb1 : b1 ∈ H)
    : b1 0 = 1 ∨ b1 1 = 1 ∨ b1 2 = 1 ∨ b1 3 = 0 ∨ b1 0 = 5 ∨ b1 1 = 5 ∨ b1 2 = 0 ∨ b1 3 = 2 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb1
  change (1 = 5 ∨ 1 = 5 ∨ 1 = 0 ∨ 0 = 2) ∨ (1 = b1 0 ∨ 1 = b1 1 ∨ 1 = b1 2 ∨ 0 = b1 3) ∨ (5 = b1 0 ∨ 5 = b1 1 ∨ 0 = b1 2 ∨ 2 = b1 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual371 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    : b2 0 = 1 ∨ b2 1 = 1 ∨ b2 2 = 1 ∨ b2 3 = 0 ∨ b2 0 = 5 ∨ b2 1 = 5 ∨ b2 2 = 0 ∨ b2 3 = 2 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb2
  change (1 = 5 ∨ 1 = 5 ∨ 1 = 0 ∨ 0 = 2) ∨ (1 = b2 0 ∨ 1 = b2 1 ∨ 1 = b2 2 ∨ 0 = b2 3) ∨ (5 = b2 0 ∨ 5 = b2 1 ∨ 0 = b2 2 ∨ 2 = b2 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual372 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b3 : NatEdge) (hb3 : b3 ∈ H)
    : b3 0 = 1 ∨ b3 1 = 1 ∨ b3 2 = 1 ∨ b3 3 = 0 ∨ b3 0 = 5 ∨ b3 1 = 5 ∨ b3 2 = 0 ∨ b3 3 = 2 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb3
  change (1 = 5 ∨ 1 = 5 ∨ 1 = 0 ∨ 0 = 2) ∨ (1 = b3 0 ∨ 1 = b3 1 ∨ 1 = b3 2 ∨ 0 = b3 3) ∨ (5 = b3 0 ∨ 5 = b3 1 ∨ 0 = b3 2 ∨ 2 = b3 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual373 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b8 : NatEdge) (hb8 : b8 ∈ H)
    : b8 0 = 1 ∨ b8 1 = 1 ∨ b8 2 = 1 ∨ b8 3 = 0 ∨ b8 0 = 5 ∨ b8 1 = 5 ∨ b8 2 = 0 ∨ b8 3 = 2 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb8
  change (1 = 5 ∨ 1 = 5 ∨ 1 = 0 ∨ 0 = 2) ∨ (1 = b8 0 ∨ 1 = b8 1 ∨ 1 = b8 2 ∨ 0 = b8 3) ∨ (5 = b8 0 ∨ 5 = b8 1 ∨ 0 = b8 2 ∨ 2 = b8 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual374 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b11 : NatEdge) (hb11 : b11 ∈ H)
    : b11 0 = 1 ∨ b11 1 = 1 ∨ b11 2 = 1 ∨ b11 3 = 0 ∨ b11 0 = 5 ∨ b11 1 = 5 ∨ b11 2 = 0 ∨ b11 3 = 2 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb11
  change (1 = 5 ∨ 1 = 5 ∨ 1 = 0 ∨ 0 = 2) ∨ (1 = b11 0 ∨ 1 = b11 1 ∨ 1 = b11 2 ∨ 0 = b11 3) ∨ (5 = b11 0 ∨ 5 = b11 1 ∨ 0 = b11 2 ∨ 2 = b11 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual375 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    (b1 : NatEdge) (hb1 : b1 ∈ H)
    : b0 0 = 1 ∨ b0 1 = 1 ∨ b0 2 = 1 ∨ b0 3 = 0 ∨ b1 0 = 1 ∨ b1 1 = 1 ∨ b1 2 = 1 ∨ b1 3 = 0 ∨ b0 0 = b1 0 ∨ b0 1 = b1 1 ∨ b0 2 = b1 2 ∨ b0 3 = b1 3 := by
  have ht := no_three_hits noThree (hF 1) hb0 hb1
  change (1 = b0 0 ∨ 1 = b0 1 ∨ 1 = b0 2 ∨ 0 = b0 3) ∨ (1 = b1 0 ∨ 1 = b1 1 ∨ 1 = b1 2 ∨ 0 = b1 3) ∨ (b0 0 = b1 0 ∨ b0 1 = b1 1 ∨ b0 2 = b1 2 ∨ b0 3 = b1 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual376 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    (b3 : NatEdge) (hb3 : b3 ∈ H)
    : b0 0 = 1 ∨ b0 1 = 1 ∨ b0 2 = 1 ∨ b0 3 = 0 ∨ b3 0 = 1 ∨ b3 1 = 1 ∨ b3 2 = 1 ∨ b3 3 = 0 ∨ b0 0 = b3 0 ∨ b0 1 = b3 1 ∨ b0 2 = b3 2 ∨ b0 3 = b3 3 := by
  have ht := no_three_hits noThree (hF 1) hb0 hb3
  change (1 = b0 0 ∨ 1 = b0 1 ∨ 1 = b0 2 ∨ 0 = b0 3) ∨ (1 = b3 0 ∨ 1 = b3 1 ∨ 1 = b3 2 ∨ 0 = b3 3) ∨ (b0 0 = b3 0 ∨ b0 1 = b3 1 ∨ b0 2 = b3 2 ∨ b0 3 = b3 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual377 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b1 : NatEdge) (hb1 : b1 ∈ H)
    (b3 : NatEdge) (hb3 : b3 ∈ H)
    : b1 0 = 1 ∨ b1 1 = 1 ∨ b1 2 = 1 ∨ b1 3 = 0 ∨ b3 0 = 1 ∨ b3 1 = 1 ∨ b3 2 = 1 ∨ b3 3 = 0 ∨ b1 0 = b3 0 ∨ b1 1 = b3 1 ∨ b1 2 = b3 2 ∨ b1 3 = b3 3 := by
  have ht := no_three_hits noThree (hF 1) hb1 hb3
  change (1 = b1 0 ∨ 1 = b1 1 ∨ 1 = b1 2 ∨ 0 = b1 3) ∨ (1 = b3 0 ∨ 1 = b3 1 ∨ 1 = b3 2 ∨ 0 = b3 3) ∨ (b1 0 = b3 0 ∨ b1 1 = b3 1 ∨ b1 2 = b3 2 ∨ b1 3 = b3 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual378 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b1 : NatEdge) (hb1 : b1 ∈ H)
    (b8 : NatEdge) (hb8 : b8 ∈ H)
    : b1 0 = 1 ∨ b1 1 = 1 ∨ b1 2 = 1 ∨ b1 3 = 0 ∨ b8 0 = 1 ∨ b8 1 = 1 ∨ b8 2 = 1 ∨ b8 3 = 0 ∨ b1 0 = b8 0 ∨ b1 1 = b8 1 ∨ b1 2 = b8 2 ∨ b1 3 = b8 3 := by
  have ht := no_three_hits noThree (hF 1) hb1 hb8
  change (1 = b1 0 ∨ 1 = b1 1 ∨ 1 = b1 2 ∨ 0 = b1 3) ∨ (1 = b8 0 ∨ 1 = b8 1 ∨ 1 = b8 2 ∨ 0 = b8 3) ∨ (b1 0 = b8 0 ∨ b1 1 = b8 1 ∨ b1 2 = b8 2 ∨ b1 3 = b8 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual379 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b1 : NatEdge) (hb1 : b1 ∈ H)
    (b11 : NatEdge) (hb11 : b11 ∈ H)
    : b1 0 = 1 ∨ b1 1 = 1 ∨ b1 2 = 1 ∨ b1 3 = 0 ∨ b11 0 = 1 ∨ b11 1 = 1 ∨ b11 2 = 1 ∨ b11 3 = 0 ∨ b1 0 = b11 0 ∨ b1 1 = b11 1 ∨ b1 2 = b11 2 ∨ b1 3 = b11 3 := by
  have ht := no_three_hits noThree (hF 1) hb1 hb11
  change (1 = b1 0 ∨ 1 = b1 1 ∨ 1 = b1 2 ∨ 0 = b1 3) ∨ (1 = b11 0 ∨ 1 = b11 1 ∨ 1 = b11 2 ∨ 0 = b11 3) ∨ (b1 0 = b11 0 ∨ b1 1 = b11 1 ∨ b1 2 = b11 2 ∨ b1 3 = b11 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual380 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    (b3 : NatEdge) (hb3 : b3 ∈ H)
    : b2 0 = 1 ∨ b2 1 = 1 ∨ b2 2 = 1 ∨ b2 3 = 0 ∨ b3 0 = 1 ∨ b3 1 = 1 ∨ b3 2 = 1 ∨ b3 3 = 0 ∨ b2 0 = b3 0 ∨ b2 1 = b3 1 ∨ b2 2 = b3 2 ∨ b2 3 = b3 3 := by
  have ht := no_three_hits noThree (hF 1) hb2 hb3
  change (1 = b2 0 ∨ 1 = b2 1 ∨ 1 = b2 2 ∨ 0 = b2 3) ∨ (1 = b3 0 ∨ 1 = b3 1 ∨ 1 = b3 2 ∨ 0 = b3 3) ∨ (b2 0 = b3 0 ∨ b2 1 = b3 1 ∨ b2 2 = b3 2 ∨ b2 3 = b3 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual381 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b3 : NatEdge) (hb3 : b3 ∈ H)
    (b10 : NatEdge) (hb10 : b10 ∈ H)
    : b3 0 = 1 ∨ b3 1 = 1 ∨ b3 2 = 1 ∨ b3 3 = 0 ∨ b10 0 = 1 ∨ b10 1 = 1 ∨ b10 2 = 1 ∨ b10 3 = 0 ∨ b10 0 = b3 0 ∨ b10 1 = b3 1 ∨ b10 2 = b3 2 ∨ b10 3 = b3 3 := by
  have ht := no_three_hits noThree (hF 1) hb3 hb10
  change (1 = b3 0 ∨ 1 = b3 1 ∨ 1 = b3 2 ∨ 0 = b3 3) ∨ (1 = b10 0 ∨ 1 = b10 1 ∨ 1 = b10 2 ∨ 0 = b10 3) ∨ (b3 0 = b10 0 ∨ b3 1 = b10 1 ∨ b3 2 = b10 2 ∨ b3 3 = b10 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual382 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 116 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 2 ∨ b0 1 = 2 ∨ b0 2 = 1 ∨ b0 3 = 1 ∨ b0 0 = 4 ∨ b0 1 = 4 ∨ b0 2 = 0 ∨ b0 3 = 2 := by
  have ht := no_three_hits noThree (hF 2) (hF 4) hb0
  change (2 = 4 ∨ 2 = 4 ∨ 1 = 0 ∨ 1 = 2) ∨ (2 = b0 0 ∨ 2 = b0 1 ∨ 1 = b0 2 ∨ 1 = b0 3) ∨ (4 = b0 0 ∨ 4 = b0 1 ∨ 0 = b0 2 ∨ 2 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (2 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 2) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))

#print axioms actual382
end Ryser.WitnessCases.Row116_105257974128.Cover
