module
public import Ryser.TwoResidualSets
public import Ryser.Theory.TemplateData
@[expose] public section
set_option maxRecDepth 8192
set_option maxHeartbeats 2000000
set_option linter.unusedVariables false
namespace Ryser.WitnessCases.Row204_113131013761.Cover
open FiniteBox TwoResidualSets
theorem actual2195 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b5 : NatEdge) (hb5 : b5 ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    : b5 0 = 0 ∨ b5 1 = 0 ∨ b5 2 = 0 ∨ b5 3 = 0 ∨ b13 0 = 0 ∨ b13 1 = 0 ∨ b13 2 = 0 ∨ b13 3 = 0 ∨ b13 0 = b5 0 ∨ b13 1 = b5 1 ∨ b13 2 = b5 2 ∨ b13 3 = b5 3 := by
  have ht := no_three_hits noThree (hF 0) hb5 hb13
  change (0 = b5 0 ∨ 0 = b5 1 ∨ 0 = b5 2 ∨ 0 = b5 3) ∨ (0 = b13 0 ∨ 0 = b13 1 ∨ 0 = b13 2 ∨ 0 = b13 3) ∨ (b5 0 = b13 0 ∨ b5 1 = b13 1 ∨ b5 2 = b13 2 ∨ b5 3 = b13 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual2196 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b5 : NatEdge) (hb5 : b5 ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    : b5 0 = 0 ∨ b5 1 = 0 ∨ b5 2 = 0 ∨ b5 3 = 0 ∨ b14 0 = 0 ∨ b14 1 = 0 ∨ b14 2 = 0 ∨ b14 3 = 0 ∨ b14 0 = b5 0 ∨ b14 1 = b5 1 ∨ b14 2 = b5 2 ∨ b14 3 = b5 3 := by
  have ht := no_three_hits noThree (hF 0) hb5 hb14
  change (0 = b5 0 ∨ 0 = b5 1 ∨ 0 = b5 2 ∨ 0 = b5 3) ∨ (0 = b14 0 ∨ 0 = b14 1 ∨ 0 = b14 2 ∨ 0 = b14 3) ∨ (b5 0 = b14 0 ∨ b5 1 = b14 1 ∨ b5 2 = b14 2 ∨ b5 3 = b14 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual2197 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b7 : NatEdge) (hb7 : b7 ∈ H)
    : b6 0 = 0 ∨ b6 1 = 0 ∨ b6 2 = 0 ∨ b6 3 = 0 ∨ b7 0 = 0 ∨ b7 1 = 0 ∨ b7 2 = 0 ∨ b7 3 = 0 ∨ b6 0 = b7 0 ∨ b6 1 = b7 1 ∨ b6 2 = b7 2 ∨ b6 3 = b7 3 := by
  have ht := no_three_hits noThree (hF 0) hb6 hb7
  change (0 = b6 0 ∨ 0 = b6 1 ∨ 0 = b6 2 ∨ 0 = b6 3) ∨ (0 = b7 0 ∨ 0 = b7 1 ∨ 0 = b7 2 ∨ 0 = b7 3) ∨ (b6 0 = b7 0 ∨ b6 1 = b7 1 ∨ b6 2 = b7 2 ∨ b6 3 = b7 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual2198 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b9 : NatEdge) (hb9 : b9 ∈ H)
    : b6 0 = 0 ∨ b6 1 = 0 ∨ b6 2 = 0 ∨ b6 3 = 0 ∨ b9 0 = 0 ∨ b9 1 = 0 ∨ b9 2 = 0 ∨ b9 3 = 0 ∨ b6 0 = b9 0 ∨ b6 1 = b9 1 ∨ b6 2 = b9 2 ∨ b6 3 = b9 3 := by
  have ht := no_three_hits noThree (hF 0) hb6 hb9
  change (0 = b6 0 ∨ 0 = b6 1 ∨ 0 = b6 2 ∨ 0 = b6 3) ∨ (0 = b9 0 ∨ 0 = b9 1 ∨ 0 = b9 2 ∨ 0 = b9 3) ∨ (b6 0 = b9 0 ∨ b6 1 = b9 1 ∨ b6 2 = b9 2 ∨ b6 3 = b9 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual2199 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b11 : NatEdge) (hb11 : b11 ∈ H)
    : b6 0 = 0 ∨ b6 1 = 0 ∨ b6 2 = 0 ∨ b6 3 = 0 ∨ b11 0 = 0 ∨ b11 1 = 0 ∨ b11 2 = 0 ∨ b11 3 = 0 ∨ b11 0 = b6 0 ∨ b11 1 = b6 1 ∨ b11 2 = b6 2 ∨ b11 3 = b6 3 := by
  have ht := no_three_hits noThree (hF 0) hb6 hb11
  change (0 = b6 0 ∨ 0 = b6 1 ∨ 0 = b6 2 ∨ 0 = b6 3) ∨ (0 = b11 0 ∨ 0 = b11 1 ∨ 0 = b11 2 ∨ 0 = b11 3) ∨ (b6 0 = b11 0 ∨ b6 1 = b11 1 ∨ b6 2 = b11 2 ∨ b6 3 = b11 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual2200 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    : b6 0 = 0 ∨ b6 1 = 0 ∨ b6 2 = 0 ∨ b6 3 = 0 ∨ b13 0 = 0 ∨ b13 1 = 0 ∨ b13 2 = 0 ∨ b13 3 = 0 ∨ b13 0 = b6 0 ∨ b13 1 = b6 1 ∨ b13 2 = b6 2 ∨ b13 3 = b6 3 := by
  have ht := no_three_hits noThree (hF 0) hb6 hb13
  change (0 = b6 0 ∨ 0 = b6 1 ∨ 0 = b6 2 ∨ 0 = b6 3) ∨ (0 = b13 0 ∨ 0 = b13 1 ∨ 0 = b13 2 ∨ 0 = b13 3) ∨ (b6 0 = b13 0 ∨ b6 1 = b13 1 ∨ b6 2 = b13 2 ∨ b6 3 = b13 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual2201 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    : b6 0 = 0 ∨ b6 1 = 0 ∨ b6 2 = 0 ∨ b6 3 = 0 ∨ b14 0 = 0 ∨ b14 1 = 0 ∨ b14 2 = 0 ∨ b14 3 = 0 ∨ b14 0 = b6 0 ∨ b14 1 = b6 1 ∨ b14 2 = b6 2 ∨ b14 3 = b6 3 := by
  have ht := no_three_hits noThree (hF 0) hb6 hb14
  change (0 = b6 0 ∨ 0 = b6 1 ∨ 0 = b6 2 ∨ 0 = b6 3) ∨ (0 = b14 0 ∨ 0 = b14 1 ∨ 0 = b14 2 ∨ 0 = b14 3) ∨ (b6 0 = b14 0 ∨ b6 1 = b14 1 ∨ b6 2 = b14 2 ∨ b6 3 = b14 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual2202 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b7 : NatEdge) (hb7 : b7 ∈ H)
    (b8 : NatEdge) (hb8 : b8 ∈ H)
    : b7 0 = 0 ∨ b7 1 = 0 ∨ b7 2 = 0 ∨ b7 3 = 0 ∨ b8 0 = 0 ∨ b8 1 = 0 ∨ b8 2 = 0 ∨ b8 3 = 0 ∨ b7 0 = b8 0 ∨ b7 1 = b8 1 ∨ b7 2 = b8 2 ∨ b7 3 = b8 3 := by
  have ht := no_three_hits noThree (hF 0) hb7 hb8
  change (0 = b7 0 ∨ 0 = b7 1 ∨ 0 = b7 2 ∨ 0 = b7 3) ∨ (0 = b8 0 ∨ 0 = b8 1 ∨ 0 = b8 2 ∨ 0 = b8 3) ∨ (b7 0 = b8 0 ∨ b7 1 = b8 1 ∨ b7 2 = b8 2 ∨ b7 3 = b8 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual2203 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b7 : NatEdge) (hb7 : b7 ∈ H)
    (b9 : NatEdge) (hb9 : b9 ∈ H)
    : b7 0 = 0 ∨ b7 1 = 0 ∨ b7 2 = 0 ∨ b7 3 = 0 ∨ b9 0 = 0 ∨ b9 1 = 0 ∨ b9 2 = 0 ∨ b9 3 = 0 ∨ b7 0 = b9 0 ∨ b7 1 = b9 1 ∨ b7 2 = b9 2 ∨ b7 3 = b9 3 := by
  have ht := no_three_hits noThree (hF 0) hb7 hb9
  change (0 = b7 0 ∨ 0 = b7 1 ∨ 0 = b7 2 ∨ 0 = b7 3) ∨ (0 = b9 0 ∨ 0 = b9 1 ∨ 0 = b9 2 ∨ 0 = b9 3) ∨ (b7 0 = b9 0 ∨ b7 1 = b9 1 ∨ b7 2 = b9 2 ∨ b7 3 = b9 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual2204 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b7 : NatEdge) (hb7 : b7 ∈ H)
    (b11 : NatEdge) (hb11 : b11 ∈ H)
    : b7 0 = 0 ∨ b7 1 = 0 ∨ b7 2 = 0 ∨ b7 3 = 0 ∨ b11 0 = 0 ∨ b11 1 = 0 ∨ b11 2 = 0 ∨ b11 3 = 0 ∨ b11 0 = b7 0 ∨ b11 1 = b7 1 ∨ b11 2 = b7 2 ∨ b11 3 = b7 3 := by
  have ht := no_three_hits noThree (hF 0) hb7 hb11
  change (0 = b7 0 ∨ 0 = b7 1 ∨ 0 = b7 2 ∨ 0 = b7 3) ∨ (0 = b11 0 ∨ 0 = b11 1 ∨ 0 = b11 2 ∨ 0 = b11 3) ∨ (b7 0 = b11 0 ∨ b7 1 = b11 1 ∨ b7 2 = b11 2 ∨ b7 3 = b11 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual2205 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b7 : NatEdge) (hb7 : b7 ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    : b7 0 = 0 ∨ b7 1 = 0 ∨ b7 2 = 0 ∨ b7 3 = 0 ∨ b13 0 = 0 ∨ b13 1 = 0 ∨ b13 2 = 0 ∨ b13 3 = 0 ∨ b13 0 = b7 0 ∨ b13 1 = b7 1 ∨ b13 2 = b7 2 ∨ b13 3 = b7 3 := by
  have ht := no_three_hits noThree (hF 0) hb7 hb13
  change (0 = b7 0 ∨ 0 = b7 1 ∨ 0 = b7 2 ∨ 0 = b7 3) ∨ (0 = b13 0 ∨ 0 = b13 1 ∨ 0 = b13 2 ∨ 0 = b13 3) ∨ (b7 0 = b13 0 ∨ b7 1 = b13 1 ∨ b7 2 = b13 2 ∨ b7 3 = b13 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual2206 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b8 : NatEdge) (hb8 : b8 ∈ H)
    (b9 : NatEdge) (hb9 : b9 ∈ H)
    : b8 0 = 0 ∨ b8 1 = 0 ∨ b8 2 = 0 ∨ b8 3 = 0 ∨ b9 0 = 0 ∨ b9 1 = 0 ∨ b9 2 = 0 ∨ b9 3 = 0 ∨ b8 0 = b9 0 ∨ b8 1 = b9 1 ∨ b8 2 = b9 2 ∨ b8 3 = b9 3 := by
  have ht := no_three_hits noThree (hF 0) hb8 hb9
  change (0 = b8 0 ∨ 0 = b8 1 ∨ 0 = b8 2 ∨ 0 = b8 3) ∨ (0 = b9 0 ∨ 0 = b9 1 ∨ 0 = b9 2 ∨ 0 = b9 3) ∨ (b8 0 = b9 0 ∨ b8 1 = b9 1 ∨ b8 2 = b9 2 ∨ b8 3 = b9 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual2207 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b8 : NatEdge) (hb8 : b8 ∈ H)
    (b11 : NatEdge) (hb11 : b11 ∈ H)
    : b8 0 = 0 ∨ b8 1 = 0 ∨ b8 2 = 0 ∨ b8 3 = 0 ∨ b11 0 = 0 ∨ b11 1 = 0 ∨ b11 2 = 0 ∨ b11 3 = 0 ∨ b11 0 = b8 0 ∨ b11 1 = b8 1 ∨ b11 2 = b8 2 ∨ b11 3 = b8 3 := by
  have ht := no_three_hits noThree (hF 0) hb8 hb11
  change (0 = b8 0 ∨ 0 = b8 1 ∨ 0 = b8 2 ∨ 0 = b8 3) ∨ (0 = b11 0 ∨ 0 = b11 1 ∨ 0 = b11 2 ∨ 0 = b11 3) ∨ (b8 0 = b11 0 ∨ b8 1 = b11 1 ∨ b8 2 = b11 2 ∨ b8 3 = b11 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual2208 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b8 : NatEdge) (hb8 : b8 ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    : b8 0 = 0 ∨ b8 1 = 0 ∨ b8 2 = 0 ∨ b8 3 = 0 ∨ b14 0 = 0 ∨ b14 1 = 0 ∨ b14 2 = 0 ∨ b14 3 = 0 ∨ b14 0 = b8 0 ∨ b14 1 = b8 1 ∨ b14 2 = b8 2 ∨ b14 3 = b8 3 := by
  have ht := no_three_hits noThree (hF 0) hb8 hb14
  change (0 = b8 0 ∨ 0 = b8 1 ∨ 0 = b8 2 ∨ 0 = b8 3) ∨ (0 = b14 0 ∨ 0 = b14 1 ∨ 0 = b14 2 ∨ 0 = b14 3) ∨ (b8 0 = b14 0 ∨ b8 1 = b14 1 ∨ b8 2 = b14 2 ∨ b8 3 = b14 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual2209 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b9 : NatEdge) (hb9 : b9 ∈ H)
    (b11 : NatEdge) (hb11 : b11 ∈ H)
    : b9 0 = 0 ∨ b9 1 = 0 ∨ b9 2 = 0 ∨ b9 3 = 0 ∨ b11 0 = 0 ∨ b11 1 = 0 ∨ b11 2 = 0 ∨ b11 3 = 0 ∨ b11 0 = b9 0 ∨ b11 1 = b9 1 ∨ b11 2 = b9 2 ∨ b11 3 = b9 3 := by
  have ht := no_three_hits noThree (hF 0) hb9 hb11
  change (0 = b9 0 ∨ 0 = b9 1 ∨ 0 = b9 2 ∨ 0 = b9 3) ∨ (0 = b11 0 ∨ 0 = b11 1 ∨ 0 = b11 2 ∨ 0 = b11 3) ∨ (b9 0 = b11 0 ∨ b9 1 = b11 1 ∨ b9 2 = b11 2 ∨ b9 3 = b11 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))

#print axioms actual2209
end Ryser.WitnessCases.Row204_113131013761.Cover
