module
public import Ryser.TwoResidualSets
public import Ryser.Theory.TemplateData
@[expose] public section
set_option maxRecDepth 8192
set_option maxHeartbeats 2000000
set_option linter.unusedVariables false
namespace Ryser.WitnessCases.Row204_113131013761.Cover
open FiniteBox TwoResidualSets
theorem actual2225 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b8 : NatEdge) (hb8 : b8 ∈ H)
    : b8 0 = 1 ∨ b8 1 = 1 ∨ b8 2 = 0 ∨ b8 3 = 1 ∨ b8 0 = 4 ∨ b8 1 = 4 ∨ b8 2 = 1 ∨ b8 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 4) hb8
  change (1 = 4 ∨ 1 = 4 ∨ 0 = 1 ∨ 1 = 0) ∨ (1 = b8 0 ∨ 1 = b8 1 ∨ 0 = b8 2 ∨ 1 = b8 3) ∨ (4 = b8 0 ∨ 4 = b8 1 ∨ 1 = b8 2 ∨ 0 = b8 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual2226 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b9 : NatEdge) (hb9 : b9 ∈ H)
    : b9 0 = 1 ∨ b9 1 = 1 ∨ b9 2 = 0 ∨ b9 3 = 1 ∨ b9 0 = 4 ∨ b9 1 = 4 ∨ b9 2 = 1 ∨ b9 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 4) hb9
  change (1 = 4 ∨ 1 = 4 ∨ 0 = 1 ∨ 1 = 0) ∨ (1 = b9 0 ∨ 1 = b9 1 ∨ 0 = b9 2 ∨ 1 = b9 3) ∨ (4 = b9 0 ∨ 4 = b9 1 ∨ 1 = b9 2 ∨ 0 = b9 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual2227 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b11 : NatEdge) (hb11 : b11 ∈ H)
    : b11 0 = 1 ∨ b11 1 = 1 ∨ b11 2 = 0 ∨ b11 3 = 1 ∨ b11 0 = 4 ∨ b11 1 = 4 ∨ b11 2 = 1 ∨ b11 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 4) hb11
  change (1 = 4 ∨ 1 = 4 ∨ 0 = 1 ∨ 1 = 0) ∨ (1 = b11 0 ∨ 1 = b11 1 ∨ 0 = b11 2 ∨ 1 = b11 3) ∨ (4 = b11 0 ∨ 4 = b11 1 ∨ 1 = b11 2 ∨ 0 = b11 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual2228 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    : b12 0 = 1 ∨ b12 1 = 1 ∨ b12 2 = 0 ∨ b12 3 = 1 ∨ b12 0 = 4 ∨ b12 1 = 4 ∨ b12 2 = 1 ∨ b12 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 4) hb12
  change (1 = 4 ∨ 1 = 4 ∨ 0 = 1 ∨ 1 = 0) ∨ (1 = b12 0 ∨ 1 = b12 1 ∨ 0 = b12 2 ∨ 1 = b12 3) ∨ (4 = b12 0 ∨ 4 = b12 1 ∨ 1 = b12 2 ∨ 0 = b12 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual2229 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    : b13 0 = 1 ∨ b13 1 = 1 ∨ b13 2 = 0 ∨ b13 3 = 1 ∨ b13 0 = 4 ∨ b13 1 = 4 ∨ b13 2 = 1 ∨ b13 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 4) hb13
  change (1 = 4 ∨ 1 = 4 ∨ 0 = 1 ∨ 1 = 0) ∨ (1 = b13 0 ∨ 1 = b13 1 ∨ 0 = b13 2 ∨ 1 = b13 3) ∨ (4 = b13 0 ∨ 4 = b13 1 ∨ 1 = b13 2 ∨ 0 = b13 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual2230 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    : b14 0 = 1 ∨ b14 1 = 1 ∨ b14 2 = 0 ∨ b14 3 = 1 ∨ b14 0 = 4 ∨ b14 1 = 4 ∨ b14 2 = 1 ∨ b14 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 4) hb14
  change (1 = 4 ∨ 1 = 4 ∨ 0 = 1 ∨ 1 = 0) ∨ (1 = b14 0 ∨ 1 = b14 1 ∨ 0 = b14 2 ∨ 1 = b14 3) ∨ (4 = b14 0 ∨ 4 = b14 1 ∨ 1 = b14 2 ∨ 0 = b14 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 4) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 1) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual2231 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b0 : NatEdge) (hb0 : b0 ∈ H)
    : b0 0 = 1 ∨ b0 1 = 1 ∨ b0 2 = 0 ∨ b0 3 = 1 ∨ b0 0 = 5 ∨ b0 1 = 5 ∨ b0 2 = 2 ∨ b0 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb0
  change (1 = 5 ∨ 1 = 5 ∨ 0 = 2 ∨ 1 = 0) ∨ (1 = b0 0 ∨ 1 = b0 1 ∨ 0 = b0 2 ∨ 1 = b0 3) ∨ (5 = b0 0 ∨ 5 = b0 1 ∨ 2 = b0 2 ∨ 0 = b0 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual2232 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b1 : NatEdge) (hb1 : b1 ∈ H)
    : b1 0 = 1 ∨ b1 1 = 1 ∨ b1 2 = 0 ∨ b1 3 = 1 ∨ b1 0 = 5 ∨ b1 1 = 5 ∨ b1 2 = 2 ∨ b1 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb1
  change (1 = 5 ∨ 1 = 5 ∨ 0 = 2 ∨ 1 = 0) ∨ (1 = b1 0 ∨ 1 = b1 1 ∨ 0 = b1 2 ∨ 1 = b1 3) ∨ (5 = b1 0 ∨ 5 = b1 1 ∨ 2 = b1 2 ∨ 0 = b1 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual2233 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    : b2 0 = 1 ∨ b2 1 = 1 ∨ b2 2 = 0 ∨ b2 3 = 1 ∨ b2 0 = 5 ∨ b2 1 = 5 ∨ b2 2 = 2 ∨ b2 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb2
  change (1 = 5 ∨ 1 = 5 ∨ 0 = 2 ∨ 1 = 0) ∨ (1 = b2 0 ∨ 1 = b2 1 ∨ 0 = b2 2 ∨ 1 = b2 3) ∨ (5 = b2 0 ∨ 5 = b2 1 ∨ 2 = b2 2 ∨ 0 = b2 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual2234 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b3 : NatEdge) (hb3 : b3 ∈ H)
    : b3 0 = 1 ∨ b3 1 = 1 ∨ b3 2 = 0 ∨ b3 3 = 1 ∨ b3 0 = 5 ∨ b3 1 = 5 ∨ b3 2 = 2 ∨ b3 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb3
  change (1 = 5 ∨ 1 = 5 ∨ 0 = 2 ∨ 1 = 0) ∨ (1 = b3 0 ∨ 1 = b3 1 ∨ 0 = b3 2 ∨ 1 = b3 3) ∨ (5 = b3 0 ∨ 5 = b3 1 ∨ 2 = b3 2 ∨ 0 = b3 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual2235 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b5 : NatEdge) (hb5 : b5 ∈ H)
    : b5 0 = 1 ∨ b5 1 = 1 ∨ b5 2 = 0 ∨ b5 3 = 1 ∨ b5 0 = 5 ∨ b5 1 = 5 ∨ b5 2 = 2 ∨ b5 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb5
  change (1 = 5 ∨ 1 = 5 ∨ 0 = 2 ∨ 1 = 0) ∨ (1 = b5 0 ∨ 1 = b5 1 ∨ 0 = b5 2 ∨ 1 = b5 3) ∨ (5 = b5 0 ∨ 5 = b5 1 ∨ 2 = b5 2 ∨ 0 = b5 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual2236 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    : b6 0 = 1 ∨ b6 1 = 1 ∨ b6 2 = 0 ∨ b6 3 = 1 ∨ b6 0 = 5 ∨ b6 1 = 5 ∨ b6 2 = 2 ∨ b6 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb6
  change (1 = 5 ∨ 1 = 5 ∨ 0 = 2 ∨ 1 = 0) ∨ (1 = b6 0 ∨ 1 = b6 1 ∨ 0 = b6 2 ∨ 1 = b6 3) ∨ (5 = b6 0 ∨ 5 = b6 1 ∨ 2 = b6 2 ∨ 0 = b6 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual2237 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b7 : NatEdge) (hb7 : b7 ∈ H)
    : b7 0 = 1 ∨ b7 1 = 1 ∨ b7 2 = 0 ∨ b7 3 = 1 ∨ b7 0 = 5 ∨ b7 1 = 5 ∨ b7 2 = 2 ∨ b7 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb7
  change (1 = 5 ∨ 1 = 5 ∨ 0 = 2 ∨ 1 = 0) ∨ (1 = b7 0 ∨ 1 = b7 1 ∨ 0 = b7 2 ∨ 1 = b7 3) ∨ (5 = b7 0 ∨ 5 = b7 1 ∨ 2 = b7 2 ∨ 0 = b7 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual2238 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b8 : NatEdge) (hb8 : b8 ∈ H)
    : b8 0 = 1 ∨ b8 1 = 1 ∨ b8 2 = 0 ∨ b8 3 = 1 ∨ b8 0 = 5 ∨ b8 1 = 5 ∨ b8 2 = 2 ∨ b8 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb8
  change (1 = 5 ∨ 1 = 5 ∨ 0 = 2 ∨ 1 = 0) ∨ (1 = b8 0 ∨ 1 = b8 1 ∨ 0 = b8 2 ∨ 1 = b8 3) ∨ (5 = b8 0 ∨ 5 = b8 1 ∨ 2 = b8 2 ∨ 0 = b8 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual2239 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 204 k ∈ H)
    (b9 : NatEdge) (hb9 : b9 ∈ H)
    : b9 0 = 1 ∨ b9 1 = 1 ∨ b9 2 = 0 ∨ b9 3 = 1 ∨ b9 0 = 5 ∨ b9 1 = 5 ∨ b9 2 = 2 ∨ b9 3 = 0 := by
  have ht := no_three_hits noThree (hF 1) (hF 5) hb9
  change (1 = 5 ∨ 1 = 5 ∨ 0 = 2 ∨ 1 = 0) ∨ (1 = b9 0 ∨ 1 = b9 1 ∨ 0 = b9 2 ∨ 1 = b9 3) ∨ (5 = b9 0 ∨ 5 = b9 1 ∨ 2 = b9 2 ∨ 0 = b9 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 5) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 2) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))

#print axioms actual2239
end Ryser.WitnessCases.Row204_113131013761.Cover
