module
public import Ryser.WitnessCases.Row204_113131013761.DataSegment0
public import Ryser.LRATBridge
@[expose] public meta section
set_option maxRecDepth 16384
set_option maxHeartbeats 4000000
namespace Ryser.WitnessCases.Row204_113131013761
def rawGroup0 : Sat.Fmla := [[Sat.Literal.neg 3, Sat.Literal.neg 2], [Sat.Literal.neg 5, Sat.Literal.neg 4], [Sat.Literal.neg 7, Sat.Literal.neg 6], [Sat.Literal.neg 9, Sat.Literal.neg 8], [Sat.Literal.neg 13, Sat.Literal.neg 12], [Sat.Literal.neg 15, Sat.Literal.neg 14], [Sat.Literal.neg 17, Sat.Literal.neg 16], [Sat.Literal.neg 19, Sat.Literal.neg 18], [Sat.Literal.neg 21, Sat.Literal.neg 20], [Sat.Literal.neg 23, Sat.Literal.neg 22], [Sat.Literal.neg 25, Sat.Literal.neg 24], [Sat.Literal.neg 1, Sat.Literal.neg 26], [Sat.Literal.neg 5, Sat.Literal.neg 28], [Sat.Literal.neg 7, Sat.Literal.neg 29], [Sat.Literal.neg 9, Sat.Literal.neg 30], [Sat.Literal.neg 11, Sat.Literal.neg 31], [Sat.Literal.neg 13, Sat.Literal.neg 32], [Sat.Literal.neg 15, Sat.Literal.neg 33], [Sat.Literal.neg 17, Sat.Literal.neg 34], [Sat.Literal.neg 21, Sat.Literal.neg 36], [Sat.Literal.neg 23, Sat.Literal.neg 37], [Sat.Literal.neg 25, Sat.Literal.neg 38], [Sat.Literal.neg 1, Sat.Literal.neg 39], [Sat.Literal.neg 3, Sat.Literal.neg 40], [Sat.Literal.neg 7, Sat.Literal.neg 42], [Sat.Literal.neg 9, Sat.Literal.neg 43], [Sat.Literal.neg 11, Sat.Literal.neg 44], [Sat.Literal.neg 17, Sat.Literal.neg 47], [Sat.Literal.neg 21, Sat.Literal.neg 49], [Sat.Literal.neg 23, Sat.Literal.neg 50], [Sat.Literal.neg 25, Sat.Literal.neg 51], [Sat.Literal.neg 1, Sat.Literal.neg 52], [Sat.Literal.neg 3, Sat.Literal.neg 53], [Sat.Literal.neg 5, Sat.Literal.neg 54], [Sat.Literal.neg 7, Sat.Literal.neg 55], [Sat.Literal.neg 1, Sat.Literal.neg 65], [Sat.Literal.neg 3, Sat.Literal.neg 66], [Sat.Literal.neg 5, Sat.Literal.neg 67], [Sat.Literal.neg 9, Sat.Literal.neg 69], [Sat.Literal.neg 11, Sat.Literal.neg 70]]
theorem group0_reify : LRATBridge.toFormula group0 = rawGroup0 := rfl
def rawGroup1 : Sat.Fmla := [[Sat.Literal.neg 13, Sat.Literal.neg 71], [Sat.Literal.neg 15, Sat.Literal.neg 72], [Sat.Literal.neg 19, Sat.Literal.neg 74], [Sat.Literal.neg 21, Sat.Literal.neg 75], [Sat.Literal.neg 23, Sat.Literal.neg 76], [Sat.Literal.neg 25, Sat.Literal.neg 77], [Sat.Literal.neg 1, Sat.Literal.neg 78], [Sat.Literal.neg 5, Sat.Literal.neg 80], [Sat.Literal.neg 7, Sat.Literal.neg 81], [Sat.Literal.neg 9, Sat.Literal.neg 82], [Sat.Literal.neg 11, Sat.Literal.neg 83], [Sat.Literal.neg 13, Sat.Literal.neg 84], [Sat.Literal.neg 15, Sat.Literal.neg 85], [Sat.Literal.neg 17, Sat.Literal.neg 86], [Sat.Literal.neg 19, Sat.Literal.neg 87], [Sat.Literal.neg 21, Sat.Literal.neg 88], [Sat.Literal.neg 23, Sat.Literal.neg 89], [Sat.Literal.neg 25, Sat.Literal.neg 90], [Sat.Literal.neg 1, Sat.Literal.neg 93, Sat.Literal.pos 7], [Sat.Literal.neg 7, Sat.Literal.neg 93, Sat.Literal.pos 1], [Sat.Literal.neg 1, Sat.Literal.neg 101, Sat.Literal.pos 23], [Sat.Literal.neg 3, Sat.Literal.neg 105, Sat.Literal.pos 9], [Sat.Literal.neg 9, Sat.Literal.neg 105, Sat.Literal.pos 3], [Sat.Literal.neg 13, Sat.Literal.neg 107, Sat.Literal.pos 3], [Sat.Literal.neg 3, Sat.Literal.neg 111, Sat.Literal.pos 23], [Sat.Literal.neg 7, Sat.Literal.neg 122, Sat.Literal.pos 9], [Sat.Literal.neg 9, Sat.Literal.neg 122, Sat.Literal.pos 7], [Sat.Literal.neg 15, Sat.Literal.neg 125, Sat.Literal.pos 7], [Sat.Literal.neg 7, Sat.Literal.neg 127, Sat.Literal.pos 19], [Sat.Literal.neg 7, Sat.Literal.neg 128, Sat.Literal.pos 21], [Sat.Literal.neg 7, Sat.Literal.neg 129, Sat.Literal.pos 23], [Sat.Literal.neg 9, Sat.Literal.neg 133, Sat.Literal.pos 15], [Sat.Literal.neg 23, Sat.Literal.neg 137, Sat.Literal.pos 9], [Sat.Literal.neg 25, Sat.Literal.neg 138, Sat.Literal.pos 9], [Sat.Literal.neg 15, Sat.Literal.neg 149, Sat.Literal.pos 19], [Sat.Literal.neg 15, Sat.Literal.neg 151, Sat.Literal.pos 25], [Sat.Literal.neg 25, Sat.Literal.neg 161, Sat.Literal.pos 23], [Sat.Literal.neg 4, Sat.Literal.neg 28], [Sat.Literal.neg 6, Sat.Literal.neg 29], [Sat.Literal.neg 8, Sat.Literal.neg 30]]
theorem group1_reify : LRATBridge.toFormula group1 = rawGroup1 := rfl
def rawGroup2 : Sat.Fmla := [[Sat.Literal.neg 12, Sat.Literal.neg 32], [Sat.Literal.neg 14, Sat.Literal.neg 33], [Sat.Literal.neg 16, Sat.Literal.neg 34], [Sat.Literal.neg 20, Sat.Literal.neg 36], [Sat.Literal.neg 22, Sat.Literal.neg 37], [Sat.Literal.neg 24, Sat.Literal.neg 38], [Sat.Literal.neg 2, Sat.Literal.neg 40], [Sat.Literal.neg 6, Sat.Literal.neg 42], [Sat.Literal.neg 8, Sat.Literal.neg 43], [Sat.Literal.neg 16, Sat.Literal.neg 47], [Sat.Literal.neg 20, Sat.Literal.neg 49], [Sat.Literal.neg 22, Sat.Literal.neg 50], [Sat.Literal.neg 24, Sat.Literal.neg 51], [Sat.Literal.neg 2, Sat.Literal.neg 53], [Sat.Literal.neg 4, Sat.Literal.neg 54], [Sat.Literal.neg 6, Sat.Literal.neg 55], [Sat.Literal.neg 8, Sat.Literal.neg 56], [Sat.Literal.neg 16, Sat.Literal.neg 60], [Sat.Literal.neg 18, Sat.Literal.neg 61], [Sat.Literal.neg 22, Sat.Literal.neg 63], [Sat.Literal.neg 2, Sat.Literal.neg 66], [Sat.Literal.neg 4, Sat.Literal.neg 67], [Sat.Literal.neg 6, Sat.Literal.neg 68], [Sat.Literal.neg 8, Sat.Literal.neg 69], [Sat.Literal.neg 12, Sat.Literal.neg 71], [Sat.Literal.neg 14, Sat.Literal.neg 72], [Sat.Literal.neg 16, Sat.Literal.neg 73], [Sat.Literal.neg 18, Sat.Literal.neg 74], [Sat.Literal.neg 20, Sat.Literal.neg 75], [Sat.Literal.neg 22, Sat.Literal.neg 76], [Sat.Literal.neg 24, Sat.Literal.neg 77], [Sat.Literal.neg 2, Sat.Literal.neg 79], [Sat.Literal.neg 4, Sat.Literal.neg 80], [Sat.Literal.neg 6, Sat.Literal.neg 81], [Sat.Literal.neg 8, Sat.Literal.neg 82], [Sat.Literal.neg 12, Sat.Literal.neg 84], [Sat.Literal.neg 14, Sat.Literal.neg 85], [Sat.Literal.neg 16, Sat.Literal.neg 86], [Sat.Literal.neg 18, Sat.Literal.neg 87], [Sat.Literal.neg 20, Sat.Literal.neg 88]]
theorem group2_reify : LRATBridge.toFormula group2 = rawGroup2 := rfl
def rawGroup3 : Sat.Fmla := [[Sat.Literal.neg 22, Sat.Literal.neg 89], [Sat.Literal.neg 24, Sat.Literal.neg 90], [Sat.Literal.neg 2, Sat.Literal.neg 91, Sat.Literal.pos 0], [Sat.Literal.neg 4, Sat.Literal.neg 92, Sat.Literal.pos 0], [Sat.Literal.neg 6, Sat.Literal.neg 93, Sat.Literal.pos 0], [Sat.Literal.neg 8, Sat.Literal.neg 94, Sat.Literal.pos 0], [Sat.Literal.neg 12, Sat.Literal.neg 96, Sat.Literal.pos 0], [Sat.Literal.neg 14, Sat.Literal.neg 97, Sat.Literal.pos 0], [Sat.Literal.neg 16, Sat.Literal.neg 98, Sat.Literal.pos 0], [Sat.Literal.neg 18, Sat.Literal.neg 99, Sat.Literal.pos 0], [Sat.Literal.neg 20, Sat.Literal.neg 100, Sat.Literal.pos 0], [Sat.Literal.neg 22, Sat.Literal.neg 101, Sat.Literal.pos 0], [Sat.Literal.neg 24, Sat.Literal.neg 102, Sat.Literal.pos 0], [Sat.Literal.neg 2, Sat.Literal.neg 105, Sat.Literal.pos 8], [Sat.Literal.neg 2, Sat.Literal.neg 8, Sat.Literal.pos 105], [Sat.Literal.neg 8, Sat.Literal.neg 105, Sat.Literal.pos 2], [Sat.Literal.neg 2, Sat.Literal.neg 106, Sat.Literal.pos 10], [Sat.Literal.neg 2, Sat.Literal.neg 108, Sat.Literal.pos 16], [Sat.Literal.neg 2, Sat.Literal.neg 16, Sat.Literal.pos 108], [Sat.Literal.neg 2, Sat.Literal.neg 109, Sat.Literal.pos 18], [Sat.Literal.neg 2, Sat.Literal.neg 110, Sat.Literal.pos 20], [Sat.Literal.neg 20, Sat.Literal.neg 110, Sat.Literal.pos 2], [Sat.Literal.neg 2, Sat.Literal.neg 111, Sat.Literal.pos 22], [Sat.Literal.neg 2, Sat.Literal.neg 112, Sat.Literal.pos 24], [Sat.Literal.neg 4, Sat.Literal.neg 113, Sat.Literal.pos 6], [Sat.Literal.neg 4, Sat.Literal.neg 114, Sat.Literal.pos 8], [Sat.Literal.neg 4, Sat.Literal.neg 115, Sat.Literal.pos 12], [Sat.Literal.neg 4, Sat.Literal.neg 116, Sat.Literal.pos 14], [Sat.Literal.neg 4, Sat.Literal.neg 117, Sat.Literal.pos 16], [Sat.Literal.neg 4, Sat.Literal.neg 118, Sat.Literal.pos 18], [Sat.Literal.neg 20, Sat.Literal.neg 119, Sat.Literal.pos 4], [Sat.Literal.neg 4, Sat.Literal.neg 120, Sat.Literal.pos 22], [Sat.Literal.neg 4, Sat.Literal.neg 121, Sat.Literal.pos 24], [Sat.Literal.neg 6, Sat.Literal.neg 122, Sat.Literal.pos 8], [Sat.Literal.neg 6, Sat.Literal.neg 8, Sat.Literal.pos 122], [Sat.Literal.neg 8, Sat.Literal.neg 122, Sat.Literal.pos 6], [Sat.Literal.neg 6, Sat.Literal.neg 123, Sat.Literal.pos 10], [Sat.Literal.neg 6, Sat.Literal.neg 124, Sat.Literal.pos 12], [Sat.Literal.neg 6, Sat.Literal.neg 125, Sat.Literal.pos 14], [Sat.Literal.neg 6, Sat.Literal.neg 14, Sat.Literal.pos 125]]
theorem group3_reify : LRATBridge.toFormula group3 = rawGroup3 := rfl

#print axioms group3_reify
end Ryser.WitnessCases.Row204_113131013761
