module
public import Ryser.TwoResidualSets
public import Ryser.Theory.TemplateData
@[expose] public section
set_option maxRecDepth 8192
set_option maxHeartbeats 2000000
set_option linter.unusedVariables false
namespace Ryser.WitnessCases.ResidualRow42_1129036992984.Cover
open FiniteBox TwoResidualSets
theorem actual3389 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    : b2 0 = 0 ∨ b2 1 = 0 ∨ b2 2 = 1 ∨ b2 3 = 0 ∨ b2 0 = 3 ∨ b2 1 = 3 ∨ b2 2 = 0 ∨ b2 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb2
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b2 0 ∨ 0 = b2 1 ∨ 1 = b2 2 ∨ 0 = b2 3) ∨ (3 = b2 0 ∨ 3 = b2 1 ∨ 0 = b2 2 ∨ 3 = b2 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual3390 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b3 : NatEdge) (hb3 : b3 ∈ H)
    : b3 0 = 0 ∨ b3 1 = 0 ∨ b3 2 = 1 ∨ b3 3 = 0 ∨ b3 0 = 3 ∨ b3 1 = 3 ∨ b3 2 = 0 ∨ b3 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb3
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b3 0 ∨ 0 = b3 1 ∨ 1 = b3 2 ∨ 0 = b3 3) ∨ (3 = b3 0 ∨ 3 = b3 1 ∨ 0 = b3 2 ∨ 3 = b3 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual3391 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b4 : NatEdge) (hb4 : b4 ∈ H)
    : b4 0 = 0 ∨ b4 1 = 0 ∨ b4 2 = 1 ∨ b4 3 = 0 ∨ b4 0 = 3 ∨ b4 1 = 3 ∨ b4 2 = 0 ∨ b4 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb4
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b4 0 ∨ 0 = b4 1 ∨ 1 = b4 2 ∨ 0 = b4 3) ∨ (3 = b4 0 ∨ 3 = b4 1 ∨ 0 = b4 2 ∨ 3 = b4 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual3392 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b5 : NatEdge) (hb5 : b5 ∈ H)
    : b5 0 = 0 ∨ b5 1 = 0 ∨ b5 2 = 1 ∨ b5 3 = 0 ∨ b5 0 = 3 ∨ b5 1 = 3 ∨ b5 2 = 0 ∨ b5 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb5
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b5 0 ∨ 0 = b5 1 ∨ 1 = b5 2 ∨ 0 = b5 3) ∨ (3 = b5 0 ∨ 3 = b5 1 ∨ 0 = b5 2 ∨ 3 = b5 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual3393 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b9 : NatEdge) (hb9 : b9 ∈ H)
    : b9 0 = 0 ∨ b9 1 = 0 ∨ b9 2 = 1 ∨ b9 3 = 0 ∨ b9 0 = 3 ∨ b9 1 = 3 ∨ b9 2 = 0 ∨ b9 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb9
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b9 0 ∨ 0 = b9 1 ∨ 1 = b9 2 ∨ 0 = b9 3) ∨ (3 = b9 0 ∨ 3 = b9 1 ∨ 0 = b9 2 ∨ 3 = b9 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual3394 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    : b12 0 = 0 ∨ b12 1 = 0 ∨ b12 2 = 1 ∨ b12 3 = 0 ∨ b12 0 = 3 ∨ b12 1 = 3 ∨ b12 2 = 0 ∨ b12 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb12
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b12 0 ∨ 0 = b12 1 ∨ 1 = b12 2 ∨ 0 = b12 3) ∨ (3 = b12 0 ∨ 3 = b12 1 ∨ 0 = b12 2 ∨ 3 = b12 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual3395 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    : b13 0 = 0 ∨ b13 1 = 0 ∨ b13 2 = 1 ∨ b13 3 = 0 ∨ b13 0 = 3 ∨ b13 1 = 3 ∨ b13 2 = 0 ∨ b13 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb13
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b13 0 ∨ 0 = b13 1 ∨ 1 = b13 2 ∨ 0 = b13 3) ∨ (3 = b13 0 ∨ 3 = b13 1 ∨ 0 = b13 2 ∨ 3 = b13 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual3396 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    : b14 0 = 0 ∨ b14 1 = 0 ∨ b14 2 = 1 ∨ b14 3 = 0 ∨ b14 0 = 3 ∨ b14 1 = 3 ∨ b14 2 = 0 ∨ b14 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb14
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b14 0 ∨ 0 = b14 1 ∨ 1 = b14 2 ∨ 0 = b14 3) ∨ (3 = b14 0 ∨ 3 = b14 1 ∨ 0 = b14 2 ∨ 3 = b14 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual3397 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b21 : NatEdge) (hb21 : b21 ∈ H)
    : b21 0 = 0 ∨ b21 1 = 0 ∨ b21 2 = 1 ∨ b21 3 = 0 ∨ b21 0 = 3 ∨ b21 1 = 3 ∨ b21 2 = 0 ∨ b21 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb21
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b21 0 ∨ 0 = b21 1 ∨ 1 = b21 2 ∨ 0 = b21 3) ∨ (3 = b21 0 ∨ 3 = b21 1 ∨ 0 = b21 2 ∨ 3 = b21 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual3398 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b22 : NatEdge) (hb22 : b22 ∈ H)
    : b22 0 = 0 ∨ b22 1 = 0 ∨ b22 2 = 1 ∨ b22 3 = 0 ∨ b22 0 = 3 ∨ b22 1 = 3 ∨ b22 2 = 0 ∨ b22 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb22
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b22 0 ∨ 0 = b22 1 ∨ 1 = b22 2 ∨ 0 = b22 3) ∨ (3 = b22 0 ∨ 3 = b22 1 ∨ 0 = b22 2 ∨ 3 = b22 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual3399 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b23 0 = 0 ∨ b23 1 = 0 ∨ b23 2 = 1 ∨ b23 3 = 0 ∨ b23 0 = 3 ∨ b23 1 = 3 ∨ b23 2 = 0 ∨ b23 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb23
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b23 0 ∨ 0 = b23 1 ∨ 1 = b23 2 ∨ 0 = b23 3) ∨ (3 = b23 0 ∨ 3 = b23 1 ∨ 0 = b23 2 ∨ 3 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual3400 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b24 : NatEdge) (hb24 : b24 ∈ H)
    : b24 0 = 0 ∨ b24 1 = 0 ∨ b24 2 = 1 ∨ b24 3 = 0 ∨ b24 0 = 3 ∨ b24 1 = 3 ∨ b24 2 = 0 ∨ b24 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb24
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b24 0 ∨ 0 = b24 1 ∨ 1 = b24 2 ∨ 0 = b24 3) ∨ (3 = b24 0 ∨ 3 = b24 1 ∨ 0 = b24 2 ∨ 3 = b24 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual3401 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b25 : NatEdge) (hb25 : b25 ∈ H)
    : b25 0 = 0 ∨ b25 1 = 0 ∨ b25 2 = 1 ∨ b25 3 = 0 ∨ b25 0 = 3 ∨ b25 1 = 3 ∨ b25 2 = 0 ∨ b25 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb25
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b25 0 ∨ 0 = b25 1 ∨ 1 = b25 2 ∨ 0 = b25 3) ∨ (3 = b25 0 ∨ 3 = b25 1 ∨ 0 = b25 2 ∨ 3 = b25 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual3402 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b26 : NatEdge) (hb26 : b26 ∈ H)
    : b26 0 = 0 ∨ b26 1 = 0 ∨ b26 2 = 1 ∨ b26 3 = 0 ∨ b26 0 = 3 ∨ b26 1 = 3 ∨ b26 2 = 0 ∨ b26 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb26
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b26 0 ∨ 0 = b26 1 ∨ 1 = b26 2 ∨ 0 = b26 3) ∨ (3 = b26 0 ∨ 3 = b26 1 ∨ 0 = b26 2 ∨ 3 = b26 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))
theorem actual3403 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b27 : NatEdge) (hb27 : b27 ∈ H)
    : b27 0 = 0 ∨ b27 1 = 0 ∨ b27 2 = 1 ∨ b27 3 = 0 ∨ b27 0 = 3 ∨ b27 1 = 3 ∨ b27 2 = 0 ∨ b27 3 = 3 := by
  have ht := no_three_hits noThree (hF 0) (hF 3) hb27
  change (0 = 3 ∨ 0 = 3 ∨ 1 = 0 ∨ 0 = 3) ∨ (0 = b27 0 ∨ 0 = b27 1 ∨ 1 = b27 2 ∨ 0 = b27 3) ∨ (3 = b27 0 ∨ 3 = b27 1 ∨ 0 = b27 2 ∨ 3 = b27 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact False.elim ((by decide : (1 : ℕ) ≠ 0) ht)
  · exact False.elim ((by decide : (0 : ℕ) ≠ 3) ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))

#print axioms actual3403
end Ryser.WitnessCases.ResidualRow42_1129036992984.Cover
