module
public import Ryser.TwoResidualSets
public import Ryser.Theory.TemplateData
@[expose] public section
set_option maxRecDepth 8192
set_option maxHeartbeats 2000000
set_option linter.unusedVariables false
namespace Ryser.WitnessCases.ResidualRow42_1129036992984.Cover
open FiniteBox TwoResidualSets
theorem actual4019 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    (b24 : NatEdge) (hb24 : b24 ∈ H)
    : b12 0 = b2 0 ∨ b12 1 = b2 1 ∨ b12 2 = b2 2 ∨ b12 3 = b2 3 ∨ b2 0 = b24 0 ∨ b2 1 = b24 1 ∨ b2 2 = b24 2 ∨ b2 3 = b24 3 ∨ b12 0 = b24 0 ∨ b12 1 = b24 1 ∨ b12 2 = b24 2 ∨ b12 3 = b24 3 := by
  have ht := no_three_hits noThree hb2 hb12 hb24
  change (b2 0 = b12 0 ∨ b2 1 = b12 1 ∨ b2 2 = b12 2 ∨ b2 3 = b12 3) ∨ (b2 0 = b24 0 ∨ b2 1 = b24 1 ∨ b2 2 = b24 2 ∨ b2 3 = b24 3) ∨ (b12 0 = b24 0 ∨ b12 1 = b24 1 ∨ b12 2 = b24 2 ∨ b12 3 = b24 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual4020 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    (b12 : NatEdge) (hb12 : b12 ∈ H)
    (b25 : NatEdge) (hb25 : b25 ∈ H)
    : b12 0 = b2 0 ∨ b12 1 = b2 1 ∨ b12 2 = b2 2 ∨ b12 3 = b2 3 ∨ b2 0 = b25 0 ∨ b2 1 = b25 1 ∨ b2 2 = b25 2 ∨ b2 3 = b25 3 ∨ b12 0 = b25 0 ∨ b12 1 = b25 1 ∨ b12 2 = b25 2 ∨ b12 3 = b25 3 := by
  have ht := no_three_hits noThree hb2 hb12 hb25
  change (b2 0 = b12 0 ∨ b2 1 = b12 1 ∨ b2 2 = b12 2 ∨ b2 3 = b12 3) ∨ (b2 0 = b25 0 ∨ b2 1 = b25 1 ∨ b2 2 = b25 2 ∨ b2 3 = b25 3) ∨ (b12 0 = b25 0 ∨ b12 1 = b25 1 ∨ b12 2 = b25 2 ∨ b12 3 = b25 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual4021 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b13 0 = b2 0 ∨ b13 1 = b2 1 ∨ b13 2 = b2 2 ∨ b13 3 = b2 3 ∨ b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3 ∨ b13 0 = b23 0 ∨ b13 1 = b23 1 ∨ b13 2 = b23 2 ∨ b13 3 = b23 3 := by
  have ht := no_three_hits noThree hb2 hb13 hb23
  change (b2 0 = b13 0 ∨ b2 1 = b13 1 ∨ b2 2 = b13 2 ∨ b2 3 = b13 3) ∨ (b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3) ∨ (b13 0 = b23 0 ∨ b13 1 = b23 1 ∨ b13 2 = b23 2 ∨ b13 3 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual4022 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b14 0 = b2 0 ∨ b14 1 = b2 1 ∨ b14 2 = b2 2 ∨ b14 3 = b2 3 ∨ b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3 ∨ b14 0 = b23 0 ∨ b14 1 = b23 1 ∨ b14 2 = b23 2 ∨ b14 3 = b23 3 := by
  have ht := no_three_hits noThree hb2 hb14 hb23
  change (b2 0 = b14 0 ∨ b2 1 = b14 1 ∨ b2 2 = b14 2 ∨ b2 3 = b14 3) ∨ (b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3) ∨ (b14 0 = b23 0 ∨ b14 1 = b23 1 ∨ b14 2 = b23 2 ∨ b14 3 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual4023 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    (b21 : NatEdge) (hb21 : b21 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b2 0 = b21 0 ∨ b2 1 = b21 1 ∨ b2 2 = b21 2 ∨ b2 3 = b21 3 ∨ b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3 ∨ b21 0 = b23 0 ∨ b21 1 = b23 1 ∨ b21 2 = b23 2 ∨ b21 3 = b23 3 := by
  have ht := no_three_hits noThree hb2 hb21 hb23
  change (b2 0 = b21 0 ∨ b2 1 = b21 1 ∨ b2 2 = b21 2 ∨ b2 3 = b21 3) ∨ (b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3) ∨ (b21 0 = b23 0 ∨ b21 1 = b23 1 ∨ b21 2 = b23 2 ∨ b21 3 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual4024 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    (b21 : NatEdge) (hb21 : b21 ∈ H)
    (b24 : NatEdge) (hb24 : b24 ∈ H)
    : b2 0 = b21 0 ∨ b2 1 = b21 1 ∨ b2 2 = b21 2 ∨ b2 3 = b21 3 ∨ b2 0 = b24 0 ∨ b2 1 = b24 1 ∨ b2 2 = b24 2 ∨ b2 3 = b24 3 ∨ b21 0 = b24 0 ∨ b21 1 = b24 1 ∨ b21 2 = b24 2 ∨ b21 3 = b24 3 := by
  have ht := no_three_hits noThree hb2 hb21 hb24
  change (b2 0 = b21 0 ∨ b2 1 = b21 1 ∨ b2 2 = b21 2 ∨ b2 3 = b21 3) ∨ (b2 0 = b24 0 ∨ b2 1 = b24 1 ∨ b2 2 = b24 2 ∨ b2 3 = b24 3) ∨ (b21 0 = b24 0 ∨ b21 1 = b24 1 ∨ b21 2 = b24 2 ∨ b21 3 = b24 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual4025 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    (b24 : NatEdge) (hb24 : b24 ∈ H)
    : b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3 ∨ b2 0 = b24 0 ∨ b2 1 = b24 1 ∨ b2 2 = b24 2 ∨ b2 3 = b24 3 ∨ b23 0 = b24 0 ∨ b23 1 = b24 1 ∨ b23 2 = b24 2 ∨ b23 3 = b24 3 := by
  have ht := no_three_hits noThree hb2 hb23 hb24
  change (b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3) ∨ (b2 0 = b24 0 ∨ b2 1 = b24 1 ∨ b2 2 = b24 2 ∨ b2 3 = b24 3) ∨ (b23 0 = b24 0 ∨ b23 1 = b24 1 ∨ b23 2 = b24 2 ∨ b23 3 = b24 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual4026 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    (b25 : NatEdge) (hb25 : b25 ∈ H)
    : b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3 ∨ b2 0 = b25 0 ∨ b2 1 = b25 1 ∨ b2 2 = b25 2 ∨ b2 3 = b25 3 ∨ b23 0 = b25 0 ∨ b23 1 = b25 1 ∨ b23 2 = b25 2 ∨ b23 3 = b25 3 := by
  have ht := no_three_hits noThree hb2 hb23 hb25
  change (b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3) ∨ (b2 0 = b25 0 ∨ b2 1 = b25 1 ∨ b2 2 = b25 2 ∨ b2 3 = b25 3) ∨ (b23 0 = b25 0 ∨ b23 1 = b25 1 ∨ b23 2 = b25 2 ∨ b23 3 = b25 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual4027 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    (b26 : NatEdge) (hb26 : b26 ∈ H)
    : b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3 ∨ b2 0 = b26 0 ∨ b2 1 = b26 1 ∨ b2 2 = b26 2 ∨ b2 3 = b26 3 ∨ b23 0 = b26 0 ∨ b23 1 = b26 1 ∨ b23 2 = b26 2 ∨ b23 3 = b26 3 := by
  have ht := no_three_hits noThree hb2 hb23 hb26
  change (b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3) ∨ (b2 0 = b26 0 ∨ b2 1 = b26 1 ∨ b2 2 = b26 2 ∨ b2 3 = b26 3) ∨ (b23 0 = b26 0 ∨ b23 1 = b26 1 ∨ b23 2 = b26 2 ∨ b23 3 = b26 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual4028 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    (b27 : NatEdge) (hb27 : b27 ∈ H)
    : b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3 ∨ b2 0 = b27 0 ∨ b2 1 = b27 1 ∨ b2 2 = b27 2 ∨ b2 3 = b27 3 ∨ b23 0 = b27 0 ∨ b23 1 = b27 1 ∨ b23 2 = b27 2 ∨ b23 3 = b27 3 := by
  have ht := no_three_hits noThree hb2 hb23 hb27
  change (b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3) ∨ (b2 0 = b27 0 ∨ b2 1 = b27 1 ∨ b2 2 = b27 2 ∨ b2 3 = b27 3) ∨ (b23 0 = b27 0 ∨ b23 1 = b27 1 ∨ b23 2 = b27 2 ∨ b23 3 = b27 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual4029 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b2 : NatEdge) (hb2 : b2 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    (b28 : NatEdge) (hb28 : b28 ∈ H)
    : b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3 ∨ b2 0 = b28 0 ∨ b2 1 = b28 1 ∨ b2 2 = b28 2 ∨ b2 3 = b28 3 ∨ b23 0 = b28 0 ∨ b23 1 = b28 1 ∨ b23 2 = b28 2 ∨ b23 3 = b28 3 := by
  have ht := no_three_hits noThree hb2 hb23 hb28
  change (b2 0 = b23 0 ∨ b2 1 = b23 1 ∨ b2 2 = b23 2 ∨ b2 3 = b23 3) ∨ (b2 0 = b28 0 ∨ b2 1 = b28 1 ∨ b2 2 = b28 2 ∨ b2 3 = b28 3) ∨ (b23 0 = b28 0 ∨ b23 1 = b28 1 ∨ b23 2 = b28 2 ∨ b23 3 = b28 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual4030 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b3 : NatEdge) (hb3 : b3 ∈ H)
    (b4 : NatEdge) (hb4 : b4 ∈ H)
    (b5 : NatEdge) (hb5 : b5 ∈ H)
    : b3 0 = b4 0 ∨ b3 1 = b4 1 ∨ b3 2 = b4 2 ∨ b3 3 = b4 3 ∨ b3 0 = b5 0 ∨ b3 1 = b5 1 ∨ b3 2 = b5 2 ∨ b3 3 = b5 3 ∨ b4 0 = b5 0 ∨ b4 1 = b5 1 ∨ b4 2 = b5 2 ∨ b4 3 = b5 3 := by
  have ht := no_three_hits noThree hb3 hb4 hb5
  change (b3 0 = b4 0 ∨ b3 1 = b4 1 ∨ b3 2 = b4 2 ∨ b3 3 = b4 3) ∨ (b3 0 = b5 0 ∨ b3 1 = b5 1 ∨ b3 2 = b5 2 ∨ b3 3 = b5 3) ∨ (b4 0 = b5 0 ∨ b4 1 = b5 1 ∨ b4 2 = b5 2 ∨ b4 3 = b5 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual4031 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b3 : NatEdge) (hb3 : b3 ∈ H)
    (b4 : NatEdge) (hb4 : b4 ∈ H)
    (b9 : NatEdge) (hb9 : b9 ∈ H)
    : b3 0 = b4 0 ∨ b3 1 = b4 1 ∨ b3 2 = b4 2 ∨ b3 3 = b4 3 ∨ b3 0 = b9 0 ∨ b3 1 = b9 1 ∨ b3 2 = b9 2 ∨ b3 3 = b9 3 ∨ b4 0 = b9 0 ∨ b4 1 = b9 1 ∨ b4 2 = b9 2 ∨ b4 3 = b9 3 := by
  have ht := no_three_hits noThree hb3 hb4 hb9
  change (b3 0 = b4 0 ∨ b3 1 = b4 1 ∨ b3 2 = b4 2 ∨ b3 3 = b4 3) ∨ (b3 0 = b9 0 ∨ b3 1 = b9 1 ∨ b3 2 = b9 2 ∨ b3 3 = b9 3) ∨ (b4 0 = b9 0 ∨ b4 1 = b9 1 ∨ b4 2 = b9 2 ∨ b4 3 = b9 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual4032 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b3 : NatEdge) (hb3 : b3 ∈ H)
    (b4 : NatEdge) (hb4 : b4 ∈ H)
    (b13 : NatEdge) (hb13 : b13 ∈ H)
    : b3 0 = b4 0 ∨ b3 1 = b4 1 ∨ b3 2 = b4 2 ∨ b3 3 = b4 3 ∨ b13 0 = b3 0 ∨ b13 1 = b3 1 ∨ b13 2 = b3 2 ∨ b13 3 = b3 3 ∨ b13 0 = b4 0 ∨ b13 1 = b4 1 ∨ b13 2 = b4 2 ∨ b13 3 = b4 3 := by
  have ht := no_three_hits noThree hb3 hb4 hb13
  change (b3 0 = b4 0 ∨ b3 1 = b4 1 ∨ b3 2 = b4 2 ∨ b3 3 = b4 3) ∨ (b3 0 = b13 0 ∨ b3 1 = b13 1 ∨ b3 2 = b13 2 ∨ b3 3 = b13 3) ∨ (b4 0 = b13 0 ∨ b4 1 = b13 1 ∨ b4 2 = b13 2 ∨ b4 3 = b13 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual4033 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 42 k ∈ H)
    (b3 : NatEdge) (hb3 : b3 ∈ H)
    (b4 : NatEdge) (hb4 : b4 ∈ H)
    (b14 : NatEdge) (hb14 : b14 ∈ H)
    : b3 0 = b4 0 ∨ b3 1 = b4 1 ∨ b3 2 = b4 2 ∨ b3 3 = b4 3 ∨ b14 0 = b3 0 ∨ b14 1 = b3 1 ∨ b14 2 = b3 2 ∨ b14 3 = b3 3 ∨ b14 0 = b4 0 ∨ b14 1 = b4 1 ∨ b14 2 = b4 2 ∨ b14 3 = b4 3 := by
  have ht := no_three_hits noThree hb3 hb4 hb14
  change (b3 0 = b4 0 ∨ b3 1 = b4 1 ∨ b3 2 = b4 2 ∨ b3 3 = b4 3) ∨ (b3 0 = b14 0 ∨ b3 1 = b14 1 ∨ b3 2 = b14 2 ∨ b3 3 = b14 3) ∨ (b4 0 = b14 0 ∨ b4 1 = b14 1 ∨ b4 2 = b14 2 ∨ b4 3 = b14 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))

#print axioms actual4033
end Ryser.WitnessCases.ResidualRow42_1129036992984.Cover
