module
public import Ryser.TwoResidualSets
public import Ryser.Theory.TemplateData
@[expose] public section
set_option maxRecDepth 8192
set_option maxHeartbeats 2000000
set_option linter.unusedVariables false
namespace Ryser.WitnessCases.ResidualRow77_1128582990184.Cover
open FiniteBox TwoResidualSets
theorem actual1998 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b1 : NatEdge) (hb1 : b1 ∈ H)
    (b17 : NatEdge) (hb17 : b17 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b1 0 = b17 0 ∨ b1 1 = b17 1 ∨ b1 2 = b17 2 ∨ b1 3 = b17 3 ∨ b1 0 = b23 0 ∨ b1 1 = b23 1 ∨ b1 2 = b23 2 ∨ b1 3 = b23 3 ∨ b17 0 = b23 0 ∨ b17 1 = b23 1 ∨ b17 2 = b23 2 ∨ b17 3 = b23 3 := by
  have ht := no_three_hits noThree hb1 hb17 hb23
  change (b1 0 = b17 0 ∨ b1 1 = b17 1 ∨ b1 2 = b17 2 ∨ b1 3 = b17 3) ∨ (b1 0 = b23 0 ∨ b1 1 = b23 1 ∨ b1 2 = b23 2 ∨ b1 3 = b23 3) ∨ (b17 0 = b23 0 ∨ b17 1 = b23 1 ∨ b17 2 = b23 2 ∨ b17 3 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual1999 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b7 : NatEdge) (hb7 : b7 ∈ H)
    (b18 : NatEdge) (hb18 : b18 ∈ H)
    : b6 0 = b7 0 ∨ b6 1 = b7 1 ∨ b6 2 = b7 2 ∨ b6 3 = b7 3 ∨ b18 0 = b6 0 ∨ b18 1 = b6 1 ∨ b18 2 = b6 2 ∨ b18 3 = b6 3 ∨ b18 0 = b7 0 ∨ b18 1 = b7 1 ∨ b18 2 = b7 2 ∨ b18 3 = b7 3 := by
  have ht := no_three_hits noThree hb6 hb7 hb18
  change (b6 0 = b7 0 ∨ b6 1 = b7 1 ∨ b6 2 = b7 2 ∨ b6 3 = b7 3) ∨ (b6 0 = b18 0 ∨ b6 1 = b18 1 ∨ b6 2 = b18 2 ∨ b6 3 = b18 3) ∨ (b7 0 = b18 0 ∨ b7 1 = b18 1 ∨ b7 2 = b18 2 ∨ b7 3 = b18 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual2000 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b7 : NatEdge) (hb7 : b7 ∈ H)
    (b19 : NatEdge) (hb19 : b19 ∈ H)
    : b6 0 = b7 0 ∨ b6 1 = b7 1 ∨ b6 2 = b7 2 ∨ b6 3 = b7 3 ∨ b19 0 = b6 0 ∨ b19 1 = b6 1 ∨ b19 2 = b6 2 ∨ b19 3 = b6 3 ∨ b19 0 = b7 0 ∨ b19 1 = b7 1 ∨ b19 2 = b7 2 ∨ b19 3 = b7 3 := by
  have ht := no_three_hits noThree hb6 hb7 hb19
  change (b6 0 = b7 0 ∨ b6 1 = b7 1 ∨ b6 2 = b7 2 ∨ b6 3 = b7 3) ∨ (b6 0 = b19 0 ∨ b6 1 = b19 1 ∨ b6 2 = b19 2 ∨ b6 3 = b19 3) ∨ (b7 0 = b19 0 ∨ b7 1 = b19 1 ∨ b7 2 = b19 2 ∨ b7 3 = b19 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual2001 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b7 : NatEdge) (hb7 : b7 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b6 0 = b7 0 ∨ b6 1 = b7 1 ∨ b6 2 = b7 2 ∨ b6 3 = b7 3 ∨ b23 0 = b6 0 ∨ b23 1 = b6 1 ∨ b23 2 = b6 2 ∨ b23 3 = b6 3 ∨ b23 0 = b7 0 ∨ b23 1 = b7 1 ∨ b23 2 = b7 2 ∨ b23 3 = b7 3 := by
  have ht := no_three_hits noThree hb6 hb7 hb23
  change (b6 0 = b7 0 ∨ b6 1 = b7 1 ∨ b6 2 = b7 2 ∨ b6 3 = b7 3) ∨ (b6 0 = b23 0 ∨ b6 1 = b23 1 ∨ b6 2 = b23 2 ∨ b6 3 = b23 3) ∨ (b7 0 = b23 0 ∨ b7 1 = b23 1 ∨ b7 2 = b23 2 ∨ b7 3 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual2002 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b7 : NatEdge) (hb7 : b7 ∈ H)
    (b25 : NatEdge) (hb25 : b25 ∈ H)
    : b6 0 = b7 0 ∨ b6 1 = b7 1 ∨ b6 2 = b7 2 ∨ b6 3 = b7 3 ∨ b25 0 = b6 0 ∨ b25 1 = b6 1 ∨ b25 2 = b6 2 ∨ b25 3 = b6 3 ∨ b25 0 = b7 0 ∨ b25 1 = b7 1 ∨ b25 2 = b7 2 ∨ b25 3 = b7 3 := by
  have ht := no_three_hits noThree hb6 hb7 hb25
  change (b6 0 = b7 0 ∨ b6 1 = b7 1 ∨ b6 2 = b7 2 ∨ b6 3 = b7 3) ∨ (b6 0 = b25 0 ∨ b6 1 = b25 1 ∨ b6 2 = b25 2 ∨ b6 3 = b25 3) ∨ (b7 0 = b25 0 ∨ b7 1 = b25 1 ∨ b7 2 = b25 2 ∨ b7 3 = b25 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht)
  · exact Or.inr (Or.inl (ht))
  · exact Or.inr (Or.inr (Or.inl (ht)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht.symm)))))))))))
theorem actual2003 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b16 : NatEdge) (hb16 : b16 ∈ H)
    (b17 : NatEdge) (hb17 : b17 ∈ H)
    : b16 0 = b6 0 ∨ b16 1 = b6 1 ∨ b16 2 = b6 2 ∨ b16 3 = b6 3 ∨ b17 0 = b6 0 ∨ b17 1 = b6 1 ∨ b17 2 = b6 2 ∨ b17 3 = b6 3 ∨ b16 0 = b17 0 ∨ b16 1 = b17 1 ∨ b16 2 = b17 2 ∨ b16 3 = b17 3 := by
  have ht := no_three_hits noThree hb6 hb16 hb17
  change (b6 0 = b16 0 ∨ b6 1 = b16 1 ∨ b6 2 = b16 2 ∨ b6 3 = b16 3) ∨ (b6 0 = b17 0 ∨ b6 1 = b17 1 ∨ b6 2 = b17 2 ∨ b6 3 = b17 3) ∨ (b16 0 = b17 0 ∨ b16 1 = b17 1 ∨ b16 2 = b17 2 ∨ b16 3 = b17 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual2004 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b16 : NatEdge) (hb16 : b16 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b16 0 = b6 0 ∨ b16 1 = b6 1 ∨ b16 2 = b6 2 ∨ b16 3 = b6 3 ∨ b23 0 = b6 0 ∨ b23 1 = b6 1 ∨ b23 2 = b6 2 ∨ b23 3 = b6 3 ∨ b16 0 = b23 0 ∨ b16 1 = b23 1 ∨ b16 2 = b23 2 ∨ b16 3 = b23 3 := by
  have ht := no_three_hits noThree hb6 hb16 hb23
  change (b6 0 = b16 0 ∨ b6 1 = b16 1 ∨ b6 2 = b16 2 ∨ b6 3 = b16 3) ∨ (b6 0 = b23 0 ∨ b6 1 = b23 1 ∨ b6 2 = b23 2 ∨ b6 3 = b23 3) ∨ (b16 0 = b23 0 ∨ b16 1 = b23 1 ∨ b16 2 = b23 2 ∨ b16 3 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual2005 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b17 : NatEdge) (hb17 : b17 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b17 0 = b6 0 ∨ b17 1 = b6 1 ∨ b17 2 = b6 2 ∨ b17 3 = b6 3 ∨ b23 0 = b6 0 ∨ b23 1 = b6 1 ∨ b23 2 = b6 2 ∨ b23 3 = b6 3 ∨ b17 0 = b23 0 ∨ b17 1 = b23 1 ∨ b17 2 = b23 2 ∨ b17 3 = b23 3 := by
  have ht := no_three_hits noThree hb6 hb17 hb23
  change (b6 0 = b17 0 ∨ b6 1 = b17 1 ∨ b6 2 = b17 2 ∨ b6 3 = b17 3) ∨ (b6 0 = b23 0 ∨ b6 1 = b23 1 ∨ b6 2 = b23 2 ∨ b6 3 = b23 3) ∨ (b17 0 = b23 0 ∨ b17 1 = b23 1 ∨ b17 2 = b23 2 ∨ b17 3 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual2006 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b18 : NatEdge) (hb18 : b18 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b18 0 = b6 0 ∨ b18 1 = b6 1 ∨ b18 2 = b6 2 ∨ b18 3 = b6 3 ∨ b23 0 = b6 0 ∨ b23 1 = b6 1 ∨ b23 2 = b6 2 ∨ b23 3 = b6 3 ∨ b18 0 = b23 0 ∨ b18 1 = b23 1 ∨ b18 2 = b23 2 ∨ b18 3 = b23 3 := by
  have ht := no_three_hits noThree hb6 hb18 hb23
  change (b6 0 = b18 0 ∨ b6 1 = b18 1 ∨ b6 2 = b18 2 ∨ b6 3 = b18 3) ∨ (b6 0 = b23 0 ∨ b6 1 = b23 1 ∨ b6 2 = b23 2 ∨ b6 3 = b23 3) ∨ (b18 0 = b23 0 ∨ b18 1 = b23 1 ∨ b18 2 = b23 2 ∨ b18 3 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual2007 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b19 : NatEdge) (hb19 : b19 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b19 0 = b6 0 ∨ b19 1 = b6 1 ∨ b19 2 = b6 2 ∨ b19 3 = b6 3 ∨ b23 0 = b6 0 ∨ b23 1 = b6 1 ∨ b23 2 = b6 2 ∨ b23 3 = b6 3 ∨ b19 0 = b23 0 ∨ b19 1 = b23 1 ∨ b19 2 = b23 2 ∨ b19 3 = b23 3 := by
  have ht := no_three_hits noThree hb6 hb19 hb23
  change (b6 0 = b19 0 ∨ b6 1 = b19 1 ∨ b6 2 = b19 2 ∨ b6 3 = b19 3) ∨ (b6 0 = b23 0 ∨ b6 1 = b23 1 ∨ b6 2 = b23 2 ∨ b6 3 = b23 3) ∨ (b19 0 = b23 0 ∨ b19 1 = b23 1 ∨ b19 2 = b23 2 ∨ b19 3 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual2008 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b20 : NatEdge) (hb20 : b20 ∈ H)
    (b21 : NatEdge) (hb21 : b21 ∈ H)
    : b20 0 = b6 0 ∨ b20 1 = b6 1 ∨ b20 2 = b6 2 ∨ b20 3 = b6 3 ∨ b21 0 = b6 0 ∨ b21 1 = b6 1 ∨ b21 2 = b6 2 ∨ b21 3 = b6 3 ∨ b20 0 = b21 0 ∨ b20 1 = b21 1 ∨ b20 2 = b21 2 ∨ b20 3 = b21 3 := by
  have ht := no_three_hits noThree hb6 hb20 hb21
  change (b6 0 = b20 0 ∨ b6 1 = b20 1 ∨ b6 2 = b20 2 ∨ b6 3 = b20 3) ∨ (b6 0 = b21 0 ∨ b6 1 = b21 1 ∨ b6 2 = b21 2 ∨ b6 3 = b21 3) ∨ (b20 0 = b21 0 ∨ b20 1 = b21 1 ∨ b20 2 = b21 2 ∨ b20 3 = b21 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual2009 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b20 : NatEdge) (hb20 : b20 ∈ H)
    (b25 : NatEdge) (hb25 : b25 ∈ H)
    : b20 0 = b6 0 ∨ b20 1 = b6 1 ∨ b20 2 = b6 2 ∨ b20 3 = b6 3 ∨ b25 0 = b6 0 ∨ b25 1 = b6 1 ∨ b25 2 = b6 2 ∨ b25 3 = b6 3 ∨ b20 0 = b25 0 ∨ b20 1 = b25 1 ∨ b20 2 = b25 2 ∨ b20 3 = b25 3 := by
  have ht := no_three_hits noThree hb6 hb20 hb25
  change (b6 0 = b20 0 ∨ b6 1 = b20 1 ∨ b6 2 = b20 2 ∨ b6 3 = b20 3) ∨ (b6 0 = b25 0 ∨ b6 1 = b25 1 ∨ b6 2 = b25 2 ∨ b6 3 = b25 3) ∨ (b20 0 = b25 0 ∨ b20 1 = b25 1 ∨ b20 2 = b25 2 ∨ b20 3 = b25 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual2010 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b6 : NatEdge) (hb6 : b6 ∈ H)
    (b21 : NatEdge) (hb21 : b21 ∈ H)
    (b25 : NatEdge) (hb25 : b25 ∈ H)
    : b21 0 = b6 0 ∨ b21 1 = b6 1 ∨ b21 2 = b6 2 ∨ b21 3 = b6 3 ∨ b25 0 = b6 0 ∨ b25 1 = b6 1 ∨ b25 2 = b6 2 ∨ b25 3 = b6 3 ∨ b21 0 = b25 0 ∨ b21 1 = b25 1 ∨ b21 2 = b25 2 ∨ b21 3 = b25 3 := by
  have ht := no_three_hits noThree hb6 hb21 hb25
  change (b6 0 = b21 0 ∨ b6 1 = b21 1 ∨ b6 2 = b21 2 ∨ b6 3 = b21 3) ∨ (b6 0 = b25 0 ∨ b6 1 = b25 1 ∨ b6 2 = b25 2 ∨ b6 3 = b25 3) ∨ (b21 0 = b25 0 ∨ b21 1 = b25 1 ∨ b21 2 = b25 2 ∨ b21 3 = b25 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual2011 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b7 : NatEdge) (hb7 : b7 ∈ H)
    (b16 : NatEdge) (hb16 : b16 ∈ H)
    (b17 : NatEdge) (hb17 : b17 ∈ H)
    : b16 0 = b7 0 ∨ b16 1 = b7 1 ∨ b16 2 = b7 2 ∨ b16 3 = b7 3 ∨ b17 0 = b7 0 ∨ b17 1 = b7 1 ∨ b17 2 = b7 2 ∨ b17 3 = b7 3 ∨ b16 0 = b17 0 ∨ b16 1 = b17 1 ∨ b16 2 = b17 2 ∨ b16 3 = b17 3 := by
  have ht := no_three_hits noThree hb7 hb16 hb17
  change (b7 0 = b16 0 ∨ b7 1 = b16 1 ∨ b7 2 = b16 2 ∨ b7 3 = b16 3) ∨ (b7 0 = b17 0 ∨ b7 1 = b17 1 ∨ b7 2 = b17 2 ∨ b7 3 = b17 3) ∨ (b16 0 = b17 0 ∨ b16 1 = b17 1 ∨ b16 2 = b17 2 ∨ b16 3 = b17 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))
theorem actual2012 (H : Finset NatEdge) (noThree : NoThreeMatching H)
    (hF : ∀ k, Theory.frozenTemplate 77 k ∈ H)
    (b7 : NatEdge) (hb7 : b7 ∈ H)
    (b16 : NatEdge) (hb16 : b16 ∈ H)
    (b23 : NatEdge) (hb23 : b23 ∈ H)
    : b16 0 = b7 0 ∨ b16 1 = b7 1 ∨ b16 2 = b7 2 ∨ b16 3 = b7 3 ∨ b23 0 = b7 0 ∨ b23 1 = b7 1 ∨ b23 2 = b7 2 ∨ b23 3 = b7 3 ∨ b16 0 = b23 0 ∨ b16 1 = b23 1 ∨ b16 2 = b23 2 ∨ b16 3 = b23 3 := by
  have ht := no_three_hits noThree hb7 hb16 hb23
  change (b7 0 = b16 0 ∨ b7 1 = b16 1 ∨ b7 2 = b16 2 ∨ b7 3 = b16 3) ∨ (b7 0 = b23 0 ∨ b7 1 = b23 1 ∨ b7 2 = b23 2 ∨ b7 3 = b23 3) ∨ (b16 0 = b23 0 ∨ b16 1 = b23 1 ∨ b16 2 = b23 2 ∨ b16 3 = b23 3) at ht
  rcases ht with (ht | ht | ht | ht) | (ht | ht | ht | ht) | (ht | ht | ht | ht)
  · exact Or.inl (ht.symm)
  · exact Or.inr (Or.inl (ht.symm))
  · exact Or.inr (Or.inr (Or.inl (ht.symm)))
  · exact Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm)))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht.symm))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl (ht)))))))))))
  · exact Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (ht)))))))))))

#print axioms actual2012
end Ryser.WitnessCases.ResidualRow77_1128582990184.Cover
